dom 14 jul 2024 22:46:35 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-contrib-20221209-1-any/usr/bin/chili-writesector b/chili-contrib-20221209-1-any/usr/bin/chili-writesector
--- a/chili-contrib-20221209-1-any/usr/bin/chili-writesector
+++ b/chili-contrib-20221209-1-any/usr/bin/chili-writesector
@@ -1,49 +1,43 @@
 #!/usr/bin/env bash
 
-function RealocarSectorDefeituoso()
-{
+function RealocarSectorDefeituoso() {
 	sectors=$(dmesg | grep $hd | grep sector | awk '{print $9}')
-	for s in $sectors
-	do
+	for s in $sectors; do
 		hdparm --yes-i-know-what-i-am-doing --write-sector $s /dev/$hd
 	done
 }
 
-function WriteOneBadSector()
-{
+function WriteOneBadSector() {
 	sector=$1
 	hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE
 }
 
-function VerifyOneBadSector()
-{
-	for count in $(seq 1 100)
-	do
-	   sector=$1
-		if ! hdparm --read-sector $sector $DEVICE &> /dev/null; then
+function VerifyOneBadSector() {
+	for count in $(seq 1 100); do
+		sector=$1
+		if ! hdparm --read-sector $sector $DEVICE &>/dev/null; then
 			echo "Failure at sector $sector"
 			echo "To fix (relocate) try the following:"
 			hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE
 		fi
-	   printf "#Pass #$count DEVICE: $DEVICE - READING SECTOR FOR ERRORS : $sector/$sector\r"
+		printf "#Pass #$count DEVICE: $DEVICE - READING SECTOR FOR ERRORS : $sector/$sector\r"
 	done
 }
 
-function VerifyAllBadSector(){
+function VerifyAllBadSector() {
 	#for dir in $(seq 1 100)
 	#do
-	   sector=1
-	   while [[ $sector != $MAX_SECTORS ]]  # but it errors if you try and read the last one, so 586072368-1
-		do
-			if ! hdparm --read-sector $sector $DEVICE &> /dev/null; then
-				echo "Failure at sector $sector"
-				echo "To fix (relocate) try the following:"
-		      echo "sudo hdparm --write-sector $sector --yes-i-know-what-i-am-doing $DEVICE"
-				hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE
-			fi
-		   printf "DEVICE: $DEVICE - READING SECTOR FOR ERRORS : $sector/$MAX_SECTORS\r"
-		   ((++sector))
-		done
+	sector=1
+	while [[ $sector != $MAX_SECTORS ]]; do # but it errors if you try and read the last one, so 586072368-1
+		if ! hdparm --read-sector $sector $DEVICE &>/dev/null; then
+			echo "Failure at sector $sector"
+			echo "To fix (relocate) try the following:"
+			echo "sudo hdparm --write-sector $sector --yes-i-know-what-i-am-doing $DEVICE"
+			hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE
+		fi
+		printf "DEVICE: $DEVICE - READING SECTOR FOR ERRORS : $sector/$MAX_SECTORS\r"
+		((++sector))
+	done
 	#done
 }
 
@@ -51,11 +45,11 @@ if test $# -ge 2; then
 	DEVICE=$1
 	MAX_SECTORS=$(fdisk -l $DEVICE | head -1 | awk '{print $7}')
 	fdisk -l $DEVICE
-#	WriteOneBadSector $2
-#	VerifyOneBadSector $*
+	#	WriteOneBadSector $2
+	#	VerifyOneBadSector $*
 	VerifyAllBadSector
 else
-cat <<EOF
+	cat <<EOF
 	usage:
 	   chili-writesector /dev/sdx nsector
 EOF
diff --git a/chili-runiso b/chili-runiso
--- a/chili-runiso
+++ b/chili-runiso
@@ -40,7 +40,7 @@ run_image() {
 			local ovmf_code='/usr/share/edk2-ovmf/x64/OVMF_CODE.fd'
 		fi
 		qemu_options+=(
-#			'-drive' "if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on"
+			#			'-drive' "if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=on"
 			'-drive' "if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=off"
 			'-drive' "if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd"
 			'-global' "driver=cfi.pflash01,property=secure,value=${secure_boot}"
@@ -61,35 +61,35 @@ run_image() {
 		)
 	fi
 
-#        -device ide-hd,drive=disk1,bootindex=1 \
-#        -boot order=d,menu=on,reboot-timeout=5000 \
-#        -device "scsi-${mediatype%rom},bus=scsi0.0,drive=${mediatype}0" \
-#			-device ide-hd,drive=disk1,bootindex=1 \
+	#        -device ide-hd,drive=disk1,bootindex=1 \
+	#        -boot order=d,menu=on,reboot-timeout=5000 \
+	#        -device "scsi-${mediatype%rom},bus=scsi0.0,drive=${mediatype}0" \
+	#			-device ide-hd,drive=disk1,bootindex=1 \
 	sudo qemu-system-x86_64 \
-		  -drive file=$image,if=none,id=disk1 \
-        -no-fd-bootchk     \
-        -m "size=8128,slots=0,maxmem=$((8128*1024*1024))" \
-        -k br-abnt2 \
-        -hda /archlive/qemu/hda.img \
-        -hdb /archlive/qemu/hdb.img \
-        -hdc /archlive/qemu/hdc.img \
-        -hdd /archlive/qemu/hdd.img \
-        -name archiso,process=archiso_0 \
-        -device virtio-scsi-pci,id=scsi0 \
-        -device "scsi-${mediatype%rom},bus=scsi0.0,drive=${mediatype}0" \
-        -drive "id=${mediatype}0,if=none,format=raw,media=${mediatype/hd/disk},read-only=on,file=${image}" \
-        -display "${display}" \
-        -vga std \
-        -audiodev pa,id=snd0,server=localhost \
-        -device ich9-intel-hda \
-        -device hda-output,audiodev=snd0 \
-        -device virtio-net-pci,romfile=,netdev=net0 -netdev user,id=net0,hostfwd=tcp::60022-:22 \
-        -machine type=q35,smm=on,accel=kvm,usb=on,pcspk-audiodev=snd0 \
-        -global ICH9-LPC.disable_s3=1 \
-         -smp 36 \
-         -enable-kvm \
-        "${qemu_options[@]}" \
-        -serial stdio
+		-drive file=$image,if=none,id=disk1 \
+		-no-fd-bootchk \
+		-m "size=8128,slots=0,maxmem=$((8128 * 1024 * 1024))" \
+		-k br-abnt2 \
+		-hda /archlive/qemu/hda.img \
+		-hdb /archlive/qemu/hdb.img \
+		-hdc /archlive/qemu/hdc.img \
+		-hdd /archlive/qemu/hdd.img \
+		-name archiso,process=archiso_0 \
+		-device virtio-scsi-pci,id=scsi0 \
+		-device "scsi-${mediatype%rom},bus=scsi0.0,drive=${mediatype}0" \
+		-drive "id=${mediatype}0,if=none,format=raw,media=${mediatype/hd/disk},read-only=on,file=${image}" \
+		-display "${display}" \
+		-vga std \
+		-audiodev pa,id=snd0,server=localhost \
+		-device ich9-intel-hda \
+		-device hda-output,audiodev=snd0 \
+		-device virtio-net-pci,romfile=,netdev=net0 -netdev user,id=net0,hostfwd=tcp::60022-:22 \
+		-machine type=q35,smm=on,accel=kvm,usb=on,pcspk-audiodev=snd0 \
+		-global ICH9-LPC.disable_s3=1 \
+		-smp 36 \
+		-enable-kvm \
+		"${qemu_options[@]}" \
+		-serial stdio
 
 }
 #		  -no-reboot
@@ -110,19 +110,28 @@ qemu_options=()
 working_dir="$(mktemp -dt run_archiso.XXXXXXXXXX)"
 trap cleanup_working_dir EXIT
 
-if (( ${#@} > 0 )); then
+if ((${#@} > 0)); then
 	while getopts 'abc:dhi:suv' flag; do
 		case "$flag" in
-			a)	accessibility='on';;
-			b)	boot_type='bios';;
-			c)	oddimage="$OPTARG";;
-			d)	mediatype='hd';;
-			h)	print_help;exit 0;;
-			i)	image="$OPTARG";;
-			u)	boot_type='uefi';;
-			s)	secure_boot='on';;
-			v)	display='none'; qemu_options+=(-vnc 'vnc=0.0.0.0:0,vnc=[::]:0');;
-			*)	printf '%s\n' "Error: Wrong option. Try 'run_archiso -h'."; exit 1;;
+		a) accessibility='on' ;;
+		b) boot_type='bios' ;;
+		c) oddimage="$OPTARG" ;;
+		d) mediatype='hd' ;;
+		h)
+			print_help
+			exit 0
+			;;
+		i) image="$OPTARG" ;;
+		u) boot_type='uefi' ;;
+		s) secure_boot='on' ;;
+		v)
+			display='none'
+			qemu_options+=(-vnc 'vnc=0.0.0.0:0,vnc=[::]:0')
+			;;
+		*)
+			printf '%s\n' "Error: Wrong option. Try 'run_archiso -h'."
+			exit 1
+			;;
 		esac
 	done
 else
diff --git a/chili-writesector b/chili-writesector
--- a/chili-writesector
+++ b/chili-writesector
@@ -5,9 +5,9 @@ function sh_config() {
 	export PS4=$'${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
 	#set -x
 	readonly DEPENDENCIES=(fdisk printf hdparm smartctl tput)
-   readonly bold=$(tput bold)
-   readonly reset=$(tput sgr0)
-	readonly black=$(tput setaf 0);
+	readonly bold=$(tput bold)
+	readonly reset=$(tput sgr0)
+	readonly black=$(tput setaf 0)
 	readonly red=$(tput setaf 1)
 	readonly green=$(tput setaf 2)
 	readonly yellow=$(tput bold)$(tput setaf 3)
@@ -16,8 +16,8 @@ function sh_config() {
 	readonly cyan=$(tput setaf 6)
 	readonly white=$(tput setaf 7)
 	readonly orange=$(tput setaf 3)
-	readonly purple=$(tput setaf 125);
-	readonly violet=$(tput setaf 61);
+	readonly purple=$(tput setaf 125)
+	readonly violet=$(tput setaf 61)
 }
 
 function sh_checkroot() {
@@ -33,7 +33,8 @@ function DOT() {
 }
 
 function die() {
-	local msg=$1; shift
+	local msg=$1
+	shift
 	printf "%-75s\n" "$(DOT)${bold}${red}$msg${reset}" >&2
 	exit 1
 }
@@ -46,7 +47,7 @@ function sh_checkDependencies() {
 	for d in "${DEPENDENCIES[@]}"; do
 		[[ -z $(command -v "$d") ]] && missing+=("$d") && errorFound=1 && printf "${red}ERROR: I couldn't find the command ${cyan}'$d'${reset}\n"
 	done
-	if (( errorFound )); then
+	if ((errorFound)); then
 		echo -e "${yellow}-------------IMPOSSIBLE TO CONTINUE-----------------${reset}"
 		echo -e "This script needs the commands listed above" >&2
 		echo -e "Install them and/or make sure they are on your \$PATH" >&2
@@ -58,8 +59,7 @@ function sh_checkDependencies() {
 
 function RealocarSectorDefeituoso() {
 	sectors=$(dmesg | grep $hd | grep sector | awk '{print $9}')
-	for s in $sectors
-	do
+	for s in $sectors; do
 		hdparm --yes-i-know-what-i-am-doing --write-sector $s /dev/$hd
 	done
 }
@@ -70,10 +70,9 @@ function WriteOneBadSector() {
 }
 
 function VerifyOneBadSector() {
-	for count in $(seq 1 100)
-	do
+	for count in $(seq 1 100); do
 		sector=$1
-		if ! hdparm --read-sector $sector $DEVICE > /dev/null; then
+		if ! hdparm --read-sector $sector $DEVICE >/dev/null; then
 			echo "Failure at sector $sector. To fix (relocate) try the following:"
 			hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE
 		fi
@@ -84,19 +83,18 @@ function VerifyOneBadSector() {
 function VerifyAllBadSector() {
 	#for dir in $(seq 1 100)
 	#do
-	   sector=1
-	   while [[ $sector != $MAX_SECTORS ]]  # but it errors if you try and read the last one, so 586072368-1
-		do
-			if ! hdparm --read-sector $sector $DEVICE >/dev/null 2>&- ; then
-				echo "${yellow}Failure at sector: $sector. Trying to fix (relocate)...${reset}"
-				if ! hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE >/dev/null 2>&- ; then
-					echo "${red}Correction/Relocation Failed:${reset}"
-					echo
-				fi
+	sector=1
+	while [[ $sector != $MAX_SECTORS ]]; do # but it errors if you try and read the last one, so 586072368-1
+		if ! hdparm --read-sector $sector $DEVICE >/dev/null 2>&-; then
+			echo "${yellow}Failure at sector: $sector. Trying to fix (relocate)...${reset}"
+			if ! hdparm --yes-i-know-what-i-am-doing --write-sector $sector $DEVICE >/dev/null 2>&-; then
+				echo "${red}Correction/Relocation Failed:${reset}"
+				echo
 			fi
-		   printf "${cyan}DEVICE: ${pink}$DEVICE - ${orange}READING SECTOR FOR ERROR : ${yellow}$sector/${red}$MAX_SECTORS\r${reset}"
-		   ((++sector))
-		done
+		fi
+		printf "${cyan}DEVICE: ${pink}$DEVICE - ${orange}READING SECTOR FOR ERROR : ${yellow}$sector/${red}$MAX_SECTORS\r${reset}"
+		((++sector))
+	done
 	#done
 }
 
@@ -110,14 +108,14 @@ if test $# -ge 1; then
 	echo -n $green
 	fdisk -l $DEVICE
 	echo $yellow
-#	WriteOneBadSector $2
-#	VerifyOneBadSector $*
+	#	WriteOneBadSector $2
+	#	VerifyOneBadSector $*
 	smartctl -d auto --health --attributes $DEVICE
 	echo -n $reset
 	VerifyAllBadSector
 else
-cat <<-EOF
-${cyan}usage:
-    ${yellow}chili-writesector /dev/sdx nsector${reset}
-EOF
+	cat <<-EOF
+		${cyan}usage:
+		    ${yellow}chili-writesector /dev/sdx nsector${reset}
+	EOF
 fi
diff --git a/debxp/contreg b/debxp/contreg
--- a/debxp/contreg
+++ b/debxp/contreg
@@ -64,30 +64,30 @@ msg_error='Wrong number of arguments!'
 # FUNCTIONS -------------------------------------------------------------------
 
 die() {
-    printf "Contreg $version\n$msg_error\n$msg_usage\n"
-    exit 1
+	printf "Contreg $version\n$msg_error\n$msg_usage\n"
+	exit 1
 }
 
 show_usage() {
-    printf "Contreg $version\n$msg_usage\n"
-    exit 0
+	printf "Contreg $version\n$msg_usage\n"
+	exit 0
 }
 
 show_version() {
-    echo "$msg_version"
-    exit 0
+	echo "$msg_version"
+	exit 0
 }
 
 # By José Almeida
 # https://gist.github.com/joseafga/7926e457175d097f52c3d8c48b78aa30
 args2seconds() {
-    local args=(0 0 "$@")
-    echo $(( ${args[-1]} + ${args[-2]}*60 + ${args[-3]}*3600 ))
+	local args=(0 0 "$@")
+	echo $((${args[-1]} + ${args[-2]} * 60 + ${args[-3]} * 3600))
 }
 
 get_term_size() {
-    term_size=($(tput lines) $(tput cols))
-    term_center=($((${term_size[0]}/2)) $((${term_size[1]}/2-4)))
+	term_size=($(tput lines) $(tput cols))
+	term_center=($((${term_size[0]} / 2)) $((${term_size[1]} / 2 - 4)))
 }
 
 # CHECKS AND INFO -------------------------------------------------------------
@@ -97,8 +97,8 @@ get_term_size() {
 
 # Usage or version options...
 case $1 in
-    h|-h|--help) show_usage;;
-    v|-v|--version) show_version;;
+h | -h | --help) show_usage ;;
+v | -v | --version) show_version ;;
 esac
 
 # CONVERSION ------------------------------------------------------------------
@@ -118,15 +118,15 @@ trap 'get_term_size' 28    # SIGWINCH
 get_term_size
 tput civis
 while [[ $secs -ge 0 ]]; do
-    tput clear
-    tput cup ${term_center[*]}
-    date -d"@$secs" -u '+%H:%M:%S'
-    ((secs--))
-    read -sN1 -t 0.995 action
-    case $action in
-        r) secs=$reset;;
-        p) read -sN1 cont;;
-        s) break;;
-    esac
+	tput clear
+	tput cup ${term_center[*]}
+	date -d"@$secs" -u '+%H:%M:%S'
+	((secs--))
+	read -sN1 -t 0.995 action
+	case $action in
+	r) secs=$reset ;;
+	p) read -sN1 cont ;;
+	s) break ;;
+	esac
 done
 tput cnorm
diff --git a/fetchpack b/fetchpack
--- a/fetchpack
+++ b/fetchpack
@@ -45,13 +45,13 @@ declare keep=3
 declare movedir=
 declare USE_COLOR='y'
 #readonly PKG_RE='(.+)-(([^-]+)-([0-9]))-([^.]+)(\.chi\.zst)'     #VC OLD
-readonly PKG_RE='(.+)-(([^-]+)-([0-9])+)-([^.]+)(\.chi\.zst)'     #VC
+readonly PKG_RE='(.+)-(([^-]+)-([0-9])+)-([^.]+)(\.chi\.zst)' #VC
 #readonly FETCH_RE='-[^-]+([0-9]+)-[0-9]+.'							   #VC
 #readonly  FETCH_RE='-[^a-z]+?[^-]+-\d.*-'							  		#VC
 #readonly FETCH_RE='-[^-]+[0-9]+-[^.]+-'										   #VC
 #readonly FETCH_RE='-[^-]+-[0-9]-'										   #VC
 #boareadonly  FETCH_RE='-[^-]+[0-9]+-([^.]+)[.]chi.*'							  		#VC
-readonly  FETCH_RE='-[^-]+[0-9]+-[^.]+.chi.*'							  		#VC
+readonly FETCH_RE='-[^-]+[0-9]+-[^.]+.chi.*' #VC
 
 # Expand to nothing if there are no matches
 shopt -s nullglob
@@ -60,7 +60,7 @@ shopt -s extglob
 # Import libs
 LIBRARY=${LIBRARY:-'/usr/share/fetch'}
 [ -e /etc/fetch/fetch.conf ] && source /etc/fetch/fetch.conf
-[ -e "$LIBRARY/core.sh"    ] && source "$LIBRARY/core.sh"
+[ -e "$LIBRARY/core.sh" ] && source "$LIBRARY/core.sh"
 export PKG_EXT="${PKG_EXT:='chi.zst'}"
 
 # flag's para split package
@@ -74,25 +74,24 @@ export PKG_EXT="${PKG_EXT:='chi.zst'}"
 : "${PKG_VERSION=5}"
 : "${PKG_BUILD=6}"
 
-sh_splitpkg()
-{
-   file="$1"
-   aPKGSPLIT=()
+sh_splitpkg() {
+	file="$1"
+	aPKGSPLIT=()
 
-   pkg_folder_dir="${file%/*}"                             #remove arquivo deixando somente o diretorio/repo
-   pkg_fullname="${file##*/}"                              #remove diretorio deixando somente nome do pacote
+	pkg_folder_dir="${file%/*}" #remove arquivo deixando somente o diretorio/repo
+	pkg_fullname="${file##*/}"  #remove diretorio deixando somente nome do pacote
 
-   [[ "$pkg_folder_dir" == "$pkg_fullname" ]] && pkg_folder_dir="localhost"
-   if [[ "$pkg_fullname" =~ $PKG_RE ]] ; then
-      pkg_fullname="${BASH_REMATCH[0]}"
-      pkg_base="${BASH_REMATCH[1]}"
-      pkg_version_build="${BASH_REMATCH[2]}"
-      pkg_version="${BASH_REMATCH[3]}"
-      pkg_build="${BASH_REMATCH[4]}"
-      pkg_arch="${BASH_REMATCH[5]}"
-      pkg_base_version="${pkg_base}-${pkg_version_build}"
+	[[ "$pkg_folder_dir" == "$pkg_fullname" ]] && pkg_folder_dir="localhost"
+	if [[ "$pkg_fullname" =~ $PKG_RE ]]; then
+		pkg_fullname="${BASH_REMATCH[0]}"
+		pkg_base="${BASH_REMATCH[1]}"
+		pkg_version_build="${BASH_REMATCH[2]}"
+		pkg_version="${BASH_REMATCH[3]}"
+		pkg_build="${BASH_REMATCH[4]}"
+		pkg_arch="${BASH_REMATCH[5]}"
+		pkg_base_version="${pkg_base}-${pkg_version_build}"
 
-:<<'comment'
+		: <<'comment'
         debug " file            : $file\n" \
               "pkg_folder_dir  : $pkg_folder_dir\n" \
               "pkg_fullname    : $pkg_fullname\n" \
@@ -102,21 +101,20 @@ sh_splitpkg()
               "pkg_version     : $pkg_version\n" \
               "pkg_build       : $pkg_build"
 comment
-      aPKGSPLIT=( "$pkg_folder_dir"
-                  "$pkg_fullname"
-                  "$pkg_arch"
-                  "$pkg_base"
-                  "$pkg_base_version"
-                  "$pkg_version-$pkg_build"
-                  "$pkg_build"
-                  )
-   fi
-   return $?
+		aPKGSPLIT=("$pkg_folder_dir"
+			"$pkg_fullname"
+			"$pkg_arch"
+			"$pkg_base"
+			"$pkg_base_version"
+			"$pkg_version-$pkg_build"
+			"$pkg_build"
+		)
+	fi
+	return $?
 }
 
 #figlet
-logo()
-{
+logo() {
 	setvarcolors
 	cat <<'EOF'
   __      _       _                      _
@@ -127,18 +125,16 @@ logo()
                        |_|
 EOF
 	echo "$yellow"
-   version
+	version
 	echo "$reset"
 }
 
-version()
-{
-	printf "%s %s\n"	"$myname" "$myver"
-	printf "%s\n"		"Copyright (C) 2020 Vilmar Catafesta <vcatafesta@gmail.com>"
+version() {
+	printf "%s %s\n" "$myname" "$myver"
+	printf "%s\n" "Copyright (C) 2020 Vilmar Catafesta <vcatafesta@gmail.com>"
 }
 
-mainOLD()
-{
+mainOLD() {
 	local arr=
 	local nfiles=
 	local pkg=
@@ -148,10 +144,9 @@ mainOLD()
 	local FilteredPackages=
 	local AllFilteredPackages=
 
-	for cachedir in "${cachedirs[@]}"
-	do
-		[[ -d "$cachedir" ]] ||	die "cachedir '%s' does not exist or is not a directory" "$cachedir"
-		if (( move || delete )); then
+	for cachedir in "${cachedirs[@]}"; do
+		[[ -d "$cachedir" ]] || die "cachedir '%s' does not exist or is not a directory" "$cachedir"
+		if ((move || delete)); then
 			[[ ! -w "$cachedir" ]] && needsroot=1
 		fi
 		pushd "$cachedir" &>/dev/null || die "failed to chdir to $cachedir"
@@ -165,28 +160,27 @@ mainOLD()
 		pkgNumber=0
 
 		if [ $# -lt 1 ]; then
-			AllFilesPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort )
+			AllFilesPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort)
 		else
 			AllFilesPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | grep "$1" | sort)
 		fi
 
 		arr=("${AllFilesPackages[*]}")
-	  	nfiles=${#arr[*]}
+		nfiles=${#arr[*]}
 
 		log_wait_msg "${reset}wait, searching ${red}($nfiles) ${reset}candidates for pruning in ${green}$cachedir"
-		for pkgInAll in $AllFilesPackages
-		do
+		for pkgInAll in $AllFilesPackages; do
 			((pkgNumber++))
 			pkgInFullName="$pkgInAll"
 			sh_splitpkg "$pkgInAll"
 			FilteredPackages="${aPKGSPLIT[$PKG_BASE]}"
 			AllFilteredPackages=$(find "$PWD" -type f -iname "$FilteredPackages*.zst" | grep -E "*$FilteredPackages-([0-9])" | sort)
 			pkg=
- 			arr=("${AllFilteredPackages[*]}")
- 			array=("${AllFilteredPackages[*]}")
-		  	nfiles=${#arr[*]}
+			arr=("${AllFilteredPackages[*]}")
+			array=("${AllFilteredPackages[*]}")
+			nfiles=${#arr[*]}
 
-			if (( verbose )); then
+			if ((verbose)); then
 				printf "     ${white}verifying package ${purple}(%04d) ${green}[%40s]${purple}(%04d)${green} => %s\n" "$pkgNumber" "$FilteredPackages" "$nfiles" "${pkgInFullName}"
 			fi
 
@@ -205,9 +199,9 @@ mainOLD()
 					if [[ "$FilteredPackages" =~ $SearchPkg ]]; then
 						if [[ $(vercmp "$pkgInFullName" "$pkg") -lt 0 ]]; then
 							candidates+=("$pkgInFullName")
-  							canddesc+=("$pkgInFullName.desc")
-						  	canddesc+=("$pkgInFullName.sha256")
-							if (( verbose >= 3 )); then
+							canddesc+=("$pkgInFullName.desc")
+							canddesc+=("$pkgInFullName.sha256")
+							if ((verbose >= 3)); then
 								[[ "$pkg" =~ $PKG_RE ]] && name="${BASH_REMATCH[1]}" arch="${BASH_REMATCH[2]}"
 								if [[ -z "$seen" || "$seenarch" != "$arch" || "$seen" != "$name" ]]; then
 									seen="$name"
@@ -215,7 +209,7 @@ mainOLD()
 									printf '%s (%s):\n' "${name##*/}" "$arch"
 								fi
 								printf '  %s\n' "${pkg##*/}"
-							elif (( verbose >= 2 )); then
+							elif ((verbose >= 2)); then
 								printf "%s$delim" "$pkg"
 							fi
 						fi
@@ -226,7 +220,7 @@ mainOLD()
 		popd >/dev/null 2>&1
 	done
 
-	if (( ! ${#candidates[*]} )); then
+	if ((!${#candidates[*]})); then
 		die "Process $nfiles: NO candidates packages found for pruning"
 	fi
 
@@ -234,26 +228,25 @@ mainOLD()
 	totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
 	set -o errexit # Exit immediately if a pipeline returns non-zero.
 
-	(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
-	if (( delete )); then
+	((verbose)) && cmdopts+=(-v)
+	cmdopts+=(-f)
+	if ((delete)); then
 		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
-		printf '%s\0' "${canddesc[@]}"   | runcmd xargs -0 rm "${cmdopts[@]}"
-	elif (( move )); then
+		printf '%s\0' "${canddesc[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+	elif ((move)); then
 		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
 	fi
 	echo
 	msg "$output (disk space saved: %s)" "$(size_to_human "$totalsaved")"
 }
 
-cleanup()
-{
+cleanup() {
 	msg "Exiting.."
 	exit
 }
 trap cleanup SIGINT SIGTERM
 
-main()
-{
+main() {
 	local nfiles=0
 	local pkg=
 	local pkgInAll=
@@ -262,56 +255,58 @@ main()
 	local cachedir
 	local re="$FETCH_RE"
 
-	if (( QUIET )); then
+	if ((QUIET)); then
 		verbose=0
 	else
-		if (( verbose )); then
-			if (( dryrun )); then
-		   	log_msg "${white}running mode => ${green}DRY-RUN"
-			elif (( delete )); then
-		   	log_msg "${white}running mode => ${red}DELETE"
-			elif (( move )); then
-		   	log_msg "${white}running mode => ${yellow}MOVE"
+		if ((verbose)); then
+			if ((dryrun)); then
+				log_msg "${white}running mode => ${green}DRY-RUN"
+			elif ((delete)); then
+				log_msg "${white}running mode => ${red}DELETE"
+			elif ((move)); then
+				log_msg "${white}running mode => ${yellow}MOVE"
 			fi
 		fi
 	fi
 
-	for cachedir in "${cachedirs[@]}"
-	do
-		[[ -d $cachedir ]]            || { log_failure_msg2 "${red}Error: cachedir '$cachedir' does not exist or is not a directory -- skipping"; continue; }
+	for cachedir in "${cachedirs[@]}"; do
+		[[ -d $cachedir ]] || {
+			log_failure_msg2 "${red}Error: cachedir '$cachedir' does not exist or is not a directory -- skipping"
+			continue
+		}
 		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
 
 		if [ $# -lt 1 ]; then
- 			AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort -Vr | awk -F "$re" 'lista[$1]++')
+			AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort -Vr | awk -F "$re" 'lista[$1]++')
 		else
- 			AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | grep "$1" | sort -Vr | awk -F "$re" 'lista[$1]++')
+			AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | grep "$1" | sort -Vr | awk -F "$re" 'lista[$1]++')
 		fi
 
 		while read -r pkgInAll; do
 			pkg_base="$pkgInAll"
-			[[ -z "$pkg_base" ]] &&	continue
+			[[ -z "$pkg_base" ]] && continue
 			((++pkgNumber))
 
-			if (( verbose >= 3 )); then
+			if ((verbose >= 3)); then
 				printf "  $(DOT)${white}candidate package ${purple}(%04d) ${green}%s\n" "$pkgNumber" "$pkg_base"
 			fi
-			[[ -e "$pkgInAll"      ]] && candidates+=("$pkgInAll")
+			[[ -e "$pkgInAll" ]] && candidates+=("$pkgInAll")
 			[[ -e "$pkgInAll.desc" ]] && candesc+=("$pkgInAll.desc")
-		done <<< "$AllOldPackages"  #done < <(printf '%s\n' "$AllOldPackages") #done <<< $(printf '%s\n' "$AllOldPackages")
+		done <<<"$AllOldPackages" #done < <(printf '%s\n' "$AllOldPackages") #done <<< $(printf '%s\n' "$AllOldPackages")
 		popd >/dev/null 2>&1
 	done
 
-	if (( ! ${#candidates[*]} )); then
+	if ((!${#candidates[*]})); then
 		log_msg "${green}NO candidates packages found for pruning"
 		exit
 	fi
 
-	if (( verbose >= 2 )); then
+	if ((verbose >= 2)); then
 		pkgNumber=0
 		while read -r pkg; do
 			((++pkgNumber))
 			printf "  $(DOT)${white}found package ${purple}(%04d) ${green}%42s\n" "$pkgNumber" "$pkg"
-		done <<< "$(printf '%s\n' "${candidates[@]}")"
+		done <<<"$(printf '%s\n' "${candidates[@]}")"
 		#done < <(printf '%s\n' "${candidates[@]}") #done <<< "${candidates[@]}"
 	fi
 
@@ -319,25 +314,27 @@ main()
 	ncandesc=${#candesc[*]}
 	pkgcount=$((ncandidates + ncandesc))
 
-	(( ncandidates )) && totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
-	(( ncandesc    )) && totalsaved+=$(printf '%s\0' "${candesc[@]}"   | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	((ncandidates)) && totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	((ncandesc)) && totalsaved+=$(printf '%s\0' "${candesc[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
 	set -o errexit # Exit immediately if a pipeline returns non-zero.
 
-	if (( delete )); then
-		(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
-		(( ncandidates )) && printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
-		(( ncandesc    )) && printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 rm "${cmdopts[@]}"
-	elif (( move )); then
-		(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
-		(( ncandidates )) && printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
-		(( ncandesc    )) && printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
-	elif (( verbose )); then
-		(( ncandidates )) && printf '%s\0' "${candidates[@]}" | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
-		(( ncandesc    )) && printf '%s\0' "${candesc[@]}"    | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
+	if ((delete)); then
+		((verbose)) && cmdopts+=(-v)
+		cmdopts+=(-f)
+		((ncandidates)) && printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+		((ncandesc)) && printf '%s\0' "${candesc[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+	elif ((move)); then
+		((verbose)) && cmdopts+=(-v)
+		cmdopts+=(-f)
+		((ncandidates)) && printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+		((ncandesc)) && printf '%s\0' "${candesc[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+	elif ((verbose)); then
+		((ncandidates)) && printf '%s\0' "${candidates[@]}" | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
+		((ncandesc)) && printf '%s\0' "${candesc[@]}" | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
 	fi
 
-	if (( ! QUIET )); then
-		if (( dryrun )); then
+	if ((!QUIET)); then
+		if ((dryrun)); then
 			msg "${yellow}$output finish dry-run (packages found: $ncandidates with .desc) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
 		else
 			msg "$output (packages found: $ncandidates with .desc) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
@@ -346,8 +343,7 @@ main()
 	return 0
 }
 
-usage()
-{
+usage() {
 	cat <<EOF
 ${cyan}Usage: ${yellow}fetch -Sc <operation> [options] [targets...]${reset}
 
@@ -370,7 +366,6 @@ ${cyan}most common use: ${yellow}fetch -Sc -k1 -r -v${reset}
 EOF
 }
 
-
 sh_checkroot
 checkDependencies
 
@@ -385,40 +380,53 @@ unset OPT_SHORT OPT_LONG OPTRET
 
 while :; do
 	case $1 in
-		-t|--ctime)
-			ctime="$2"
-			shift ;;
-		-c|--cachedir)
-			cachedirs+=("$2")
-			shift ;;
-		-d|--dryrun)
-			dryrun=1 ;;
-		-f|--force)
-			cmdopts=(-f) ;;
-		-h|--help)
-			usage
-			exit 0 ;;
-		-m|--move)
-			move=1 movedir=$2
-			shift ;;
-		--nocolor)
-			unsetvarcolors
-			USE_COLOR='n' ;;
-		-q|--quiet)
-			unsetvarcolors
-			QUIET=1 ;;
-		-r|--remove)
-			delete=1 ;;
-		-V|--version)
-			logo
-			exit 0 ;;
-		-v|--verbose)
-			(( ++verbose )) ;;
-		-z|--null)
-			delim='\0' ;;
-		--)
-			shift
-			break 2 ;;
+	-t | --ctime)
+		ctime="$2"
+		shift
+		;;
+	-c | --cachedir)
+		cachedirs+=("$2")
+		shift
+		;;
+	-d | --dryrun)
+		dryrun=1
+		;;
+	-f | --force)
+		cmdopts=(-f)
+		;;
+	-h | --help)
+		usage
+		exit 0
+		;;
+	-m | --move)
+		move=1 movedir=$2
+		shift
+		;;
+	--nocolor)
+		unsetvarcolors
+		USE_COLOR='n'
+		;;
+	-q | --quiet)
+		unsetvarcolors
+		QUIET=1
+		;;
+	-r | --remove)
+		delete=1
+		;;
+	-V | --version)
+		logo
+		exit 0
+		;;
+	-v | --verbose)
+		((++verbose))
+		;;
+	-z | --null)
+		delim='\0'
+		;;
+	--)
+		shift
+		break 2
+		;;
 	esac
 	shift
 done
@@ -435,14 +443,14 @@ if [[ -z "${cachedirs[*]}" ]]; then
 fi
 
 # sanity checks
-case $(( dryrun+delete+move )) in
-	0) 	die "no operation specified (use -h for help)" ;;
-	[^1]) die "only one operation may be used at a time" ;;
+case $((dryrun + delete + move)) in
+0) die "no operation specified (use -h for help)" ;;
+[^1]) die "only one operation may be used at a time" ;;
 esac
 
 [[ $movedir && ! -d $movedir ]] && die "destination directory '$movedir' does not exist or is not a directory!"
 
-if (( move || delete )); then
+if ((move || delete)); then
 	# make it an absolute path since we're about to chdir
 	[[ $movedir && ${movedir:0:1} != '/' ]] && movedir=$PWD/$movedir
 	[[ $movedir && ! -w $movedir ]] && needsroot=1
