sex 07 mar 2025 23:30:49 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-maketar b/chili-maketar
--- a/chili-maketar
+++ b/chili-maketar
@@ -40,8 +40,8 @@ shopt -s extglob
 readonly APP="${0##*/}"
 readonly APPDESC="Create tar of directories"
 readonly _VERSION_="1.3.07-20250307"
-readonly DEPENDENCIES=(tar tput sed pigz pzstd xz gzip vilmar)
-readonly PACKAGEDEP=(tar ncurses sed pigz zstd xz gzip vilmar)
+readonly DEPENDENCIES=(tar tput sed pigz pzstd xz gzip)
+readonly PACKAGEDEP=(tar ncurses sed pigz zstd xz gzip)
 
 function sh_diahora {
 	#	DIAHORA=$(date +"%d%m%Y-%T" | sed 's/://g')
@@ -54,7 +54,7 @@ function sh_config {
 	declare -g CROSS="${white}[${COL_LIGHT_RED}✗${COL_NC}$white]"
 	declare -g BOOTLOG="/tmp/$APP-$(sh_diahora).log"
 	declare -g LOGGER='/dev/tty8'
-	declare -g quiet=false
+	declare -g quiet=true
 	declare -g use_color=true
 	declare -gi ncontador=1
 	declare -gi njobs=0
@@ -68,8 +68,8 @@ function log_error {
 }
 
 msg() {
-   local msg="$1"
-   echo -e "==>${cyan}[INFO] ${yellow}${msg}${reset}"
+	local msg="$1"
+	echo -e "==>${cyan}[INFO] ${yellow}${msg}${reset}"
 }
 
 function cmdlogger {
@@ -82,9 +82,9 @@ function cmdlogger {
 	info_msg "Running '$*'"
 	#   error_output=$( "$@" 2>&1 )
 	if $quiet; then
-  	eval "$@" 2>&1 | tee -i -a "$BOOTLOG" >"$LOGGER"
-  else
-	  eval "$@" | tee -i -a "$BOOTLOG"
+		eval "$@" 2>&1 | tee -i -a "$BOOTLOG" >"$LOGGER"
+	else
+		eval "$@" | tee -i -a "$BOOTLOG"
 	fi
 	#  status="${PIPESTATUS[0]}"
 	status="$?"
@@ -96,7 +96,7 @@ function cmdlogger {
 }
 
 function sh_check_terminal {
-  if [ ! -t 1 ]; then
+	if [ ! -t 1 ]; then
 		use_color=false
 	fi
 }
@@ -126,7 +126,7 @@ function sh_setvarcolors {
 
 die() {
 	((++njobs))
-  printf "${red}$CROSS ${pink}%03d/%03d => ${red}FATAL: %s\n\033[m" "$ncontador" "$njobs" "$@"
+	printf "${red}$CROSS ${pink}%03d/%03d => ${red}FATAL: %s\n\033[m" "$ncontador" "$njobs" "$@"
 	((++ncontador))
 	exit 1
 }
@@ -153,41 +153,41 @@ function sh_checkDependencies() {
 	done
 
 	if $errorFound; then
-	   if ! sudo pacman -Sy "${PACKAGEDEP[@]}" --needed --noconfirm 1>/dev/null ; then
-         echo
-         msg "${yellow}----------------------IMPOSSÍVEL CONTINUAR--------------------${reset}"
-         msg "Este script precisa dos comandos listados acima.${reset}"
-         msg "Fiz tentativa de instalar, no entanto falhou.${reset}"
-         msg "Instale-os e/ou certifique-se de que eles estejam em seu ${red}\$PATH${reset}"
-         msg "${yellow}----------------------IMPOSSÍVEL CONTINUAR--------------------${reset}"
-         die "Instalação abortada!"
-      fi
+		if ! sudo pacman -Sy "${PACKAGEDEP[@]}" --needed --noconfirm 1>/dev/null; then
+			echo
+			msg "${yellow}----------------------IMPOSSÍVEL CONTINUAR--------------------${reset}"
+			msg "Este script precisa dos comandos listados acima.${reset}"
+			msg "Fiz tentativa de instalar, no entanto falhou.${reset}"
+			msg "Instale-os e/ou certifique-se de que eles estejam em seu ${red}\$PATH${reset}"
+			msg "${yellow}----------------------IMPOSSÍVEL CONTINUAR--------------------${reset}"
+			die "Instalação abortada!"
+		fi
 	fi
 }
 
 function sh_main {
-  if [[ "$1" == '.' ]]; then
-    directory=$(basename "$(pwd)")
-  else
-    directory="${1%/}"
-  fi
+	if [[ "$1" == '.' ]]; then
+		directory=$(basename "$(pwd)")
+	else
+		directory="${1%/}"
+	fi
 	local FILENAME=$directory-$(sh_diahora).tar
 	local error
 	local param='--verbose'
 
-  if $quiet; then
-    param=''
-  fi
+	if $quiet; then
+		param=''
+	fi
 
 	case "$compressor" in
 	pigz)
 		FILENAME+=".gz"
- 		cmdlogger tar -I pigz $param --posix --xattrs -chf "$FILENAME" "$1"
+		cmdlogger tar -I pigz $param --posix --xattrs -chf "$FILENAME" "$1"
 		;;
 	pzstd)
 		FILENAME+=".zst"
-#   cmdlogger tar --use-compress-program="pzstd -19" --verbose --posix --xattrs -chf chililinux-26122024-1235.tar.zst chililinux
- 		cmdlogger tar -I pzstd $param --posix --xattrs -chf "$FILENAME" "$1"
+		#   cmdlogger tar --use-compress-program="pzstd -19" --verbose --posix --xattrs -chf chililinux-26122024-1235.tar.zst chililinux
+		cmdlogger tar -I pzstd $param --posix --xattrs -chf "$FILENAME" "$1"
 		;;
 	gzip)
 		FILENAME+=".gz"
@@ -212,27 +212,27 @@ function sh_main {
 }
 
 sh_usage() {
-   cat <<-EOF
-    ${cyan}$APP - $APPDESC${reset}
-    Uso: $APP [options] <directory>
+	cat <<-EOF
+		    ${cyan}$APP - $APPDESC${reset}
+		    Uso: $APP [options] <directory>
 
-    Options:
-      -q          Quiet mode (suppress progress messages)
-      -n          Disable colors in the output
-      -z          Use pigz for compression
-      -s          Use pzstd for compression (default)
-      -g          Use gzip for compression
-      -x          Use xz for compression
-      (normal)    Create tar archive without additional compression
-EOF
-   exit 1
+		    Options:
+		      -v          Verbose mode (progress messages)
+		      -n          Disable colors in the output
+		      -z          Use pigz for compression
+		      -s          Use pzstd for compression (default)
+		      -g          Use gzip for compression
+		      -x          Use xz for compression
+		      (normal)    Create tar archive without additional compression
+	EOF
+	exit 1
 }
 
 sh_config
 
 # Display usage information if no arguments are passed
 if [[ $# -eq 0 || $1 = @(-h|--help) || $1 = "-h" || $1 = "--help" || $1 = "help" || $1 = "-help" ]]; then
-   sh_usage
+	sh_usage
 fi
 
 sh_checkDependencies
@@ -241,29 +241,48 @@ sh_checkDependencies
 #	die "$APP: need root perms to continue, exiting."
 #fi
 if test -w "$PWD"; then
-  info_msg "$USER com gravação permitida em $PWD, prosseguindo..."
+	info_msg "$USER com gravação permitida em $PWD, prosseguindo..."
 else
-  info_msg "$USER sem permissão de gravação em $PWD"
-  if [ "$(id -u)" -ne 0 ]; then
-    die "$APP: need root perms to continue, exiting."
-  fi
+	info_msg "$USER sem permissão de gravação em $PWD"
+	if [ "$(id -u)" -ne 0 ]; then
+		die "$APP: need root perms to continue, exiting."
+	fi
 fi
 
 # Process command line options using getopts
 while getopts "qnsxzg" opt; do
-  case $opt in
-    q) quiet=true;info_msg 'Param -q detected, disabling verbose'             ;; # Quiet mode
-    n) use_color=false;sh_setvarcolors;info_msg 'Param -n detected, disabling colors';; # Disable color
-    z) compressor="pigz";info_msg "Param -z detected, compressor is now '$compressor'";; # Use pigz for compression
-    s) compressor="pzstd";info_msg "Param -z detected, compressor is now '$compressor'"     ;; # Use pzstd for compression
-    g) compressor="gzip";info_msg "Param -z detected, compressor is now '$compressor'"      ;; # Use gzip for compression
-    x) compressor="xz";info_msg "Param -z detected, compressor is now '$compressor'"        ;; # Use xz for compression
-    \?) die "Invalid option: -$OPTARG";;
-  esac
+	case $opt in
+	v)
+		quiet=false
+		info_msg 'Param -v detected, enabling verbose'
+		;;
+	n)
+		use_color=false
+		sh_setvarcolors
+		info_msg 'Param -n detected, disabling colors'
+		;; # Disable color
+	z)
+		compressor="pigz"
+		info_msg "Param -z detected, compressor is now '$compressor'"
+		;; # Use pigz for compression
+	s)
+		compressor="pzstd"
+		info_msg "Param -z detected, compressor is now '$compressor'"
+		;; # Use pzstd for compression
+	g)
+		compressor="gzip"
+		info_msg "Param -z detected, compressor is now '$compressor'"
+		;; # Use gzip for compression
+	x)
+		compressor="xz"
+		info_msg "Param -z detected, compressor is now '$compressor'"
+		;; # Use xz for compression
+	\?) die "Invalid option: -$OPTARG" ;;
+	esac
 done
 
 # Process the remaining argument (directory)
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 
 # Check if the directory argument is missing or invalid
 [[ -z "$1" || ! -d "$1" ]] && die "${cyan}argument directory ${yellow}'$1' ${reset}is either missing or does not exist!"
