ter 26 nov 2024 23:43:46 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-make-repo b/chili-make-repo
--- a/chili-make-repo
+++ b/chili-make-repo
@@ -186,26 +186,42 @@ main() {
 
 sh_synchronize_remote_with_local() {
 	sh_config
-	[[ -z "$branch" ]] && branch="testing"
-	remote_DOMAIN="repo"
-	remote_PATH="/home/${remote_USER}/domains/chililinux.com/public_html/${remote_DOMAIN}/${branch,,}/x86_64"
-	local_PATH="/github/ChiliOS/packages/core/${branch,,}/x86_64"
+	if [[ -z "$branch" ]]; then
+		aBranchs=('testing')
+	elif [[ "$branch" == 'stable' ]]; then
+		local aBranchs=('stable')
+	elif [[ "$branch" == 'testing' ]]; then
+		local aBranchs=('testing')
+	elif [[ "$branch" == 'extra' ]]; then
+		local aBranchs=('extra')
+	elif [[ "$branch" == 'all' ]]; then
+		local aBranchs=('stable' 'testing' 'extra')
+	fi
 
-	echo "${cyan}Sincronizando repositório remoto com local - branch: $branch ${reset}"
-	echo "${cyan}Puxando do remoto para local ${reset}"
-	rsync --progress --delete -Craz -e 'ssh -p 65002' ${remote_USER}@${remote_HOST}:${remote_PATH}/ ${local_PATH}/
+	for branch in "${aBranchs[@]}"; do
+		remote_DOMAIN="repo"
+		remote_PATH="/home/${remote_USER}/domains/chililinux.com/public_html/${remote_DOMAIN}/${branch,,}/x86_64"
+		local_PATH="/github/ChiliOS/packages/core/${branch,,}/x86_64"
 
-	AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort -Vr | awk -F "$FETCH_RE" 'lista[$1]++')
-	for old in ${AllOldPackages[@]}; do
-		echo "Removing old package: [$((++count))] $old"
-		rm -fv "${old}" "${old}.sig" "${old}.md5" "${old}.sig.md5"
+		pushd "$local_PATH" || exit 1
+		echo "${cyan}Sincronizando repositório remoto com local - branch: $branch ${reset}"
+		echo "${cyan}Puxando do remoto para local ${reset}"
+		rsync --progress --delete -Craz -e 'ssh -p 65002' ${remote_USER}@${remote_HOST}:${remote_PATH}/ ${local_PATH}/
+    rm -f chili-${branch}*
+
+		AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort -Vr | awk -F "$FETCH_RE" 'lista[$1]++')
+		for old in ${AllOldPackages[@]}; do
+			echo "Removing old package: [$((++count))] $old"
+			rm -fv "${old}" "${old}.sig" "${old}.md5" "${old}.sig.md5"
+		done
+
+		echo "${cyan}Criando Database (.db) localmente ${reset}"
+		repo-add -q -p -n -R chili-${branch}.db.tar.gz *.pkg.tar.zst
+		echo "${cyan}Empurrando para o remoto ${reset}"
+		rsync --progress --delete -Craz -e 'ssh -p 65002' ${local_PATH}/ ${remote_USER}@${remote_HOST}:${remote_PATH}/
+		popd || exit 1
 	done
-
-	echo "${cyan}Criando Database (.db) localmente ${reset}"
-	repo-add -q -p -n -R chili-${branch}.db.tar.gz *.pkg.tar.zst
-	echo "${cyan}Empurrando para o remoto ${reset}"
-	rsync --progress --delete -Craz -e 'ssh -p 65002' ${local_PATH}/ ${remote_USER}@${remote_HOST}:${remote_PATH}/
-  exit $(($# ? 0 : 1))
+	exit $(($# ? 0 : 1))
 }
 
 if test $# -lt 1; then
@@ -236,12 +252,12 @@ for arg in "$@"; do
 		next_arg="${2:-}"
 
 		# Verifica se o próximo argumento é válido
-		if [[ "$next_arg" =~ ^(stable|testing|extra)$ ]]; then
-      branch="$next_arg"
+		if [[ "$next_arg" =~ ^(stable|testing|extra|all)$ ]]; then
+			branch="$next_arg"
 			sh_synchronize_remote_with_local "$next_arg"
 			shift # Pula para o próximo argumento para não ser tratado novamente
 		else
-			echo "${red}Error: Opção inválida para --synchronize: $next_arg. Use ${yellow}'stable', 'testing' ou 'extra'.${reset}"
+			echo "${red}Error: Opção inválida para --synchronize: $next_arg. Use ${yellow}'stable', 'testing', 'extra' ou 'all'${reset}"
 			exit 1
 		fi
 	else
