sex 07 mar 2025 12:29:33 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-maketar b/chili-maketar
--- a/chili-maketar
+++ b/chili-maketar
@@ -2,14 +2,13 @@
 #shellcheck disable=SC2155,SC2034
 #shellcheck source=/dev/null
 
-#  chili-maketar
-#  Description: Create tar of directories
+#  chili-maketar - Create tar of directories
 #
 #  Created: 2023/07/28
 #  Altered: 2023/07/28
-#  Updated: 2024/12/25 - 03:42:08 -04 - Added gzip, xz, and normal tar support
+#  Updated: sex 07 mar 2025 12:18:52 -04
 #
-#  Copyright (c) 2023-2023, Vilmar Catafesta <vcatafesta@gmail.com>
+#  Copyright (c) 2023-2025, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -39,8 +38,10 @@ export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
 shopt -s extglob
 
 readonly APP="${0##*/}"
-readonly _VERSION_="1.0.0-20230728"
-readonly DEPENDENCIES=(tar tput sed pigz pzstd xz gzip)
+readonly APPDESC="Create tar of directories"
+readonly _VERSION_="1.3.07-20250307"
+readonly DEPENDENCIES=(tar tput sed pigz pzstd xz gzip vilmar)
+readonly PACKAGEDEP=(tar ncurses sed pigz zstd xz gzip vilmar)
 
 function sh_diahora {
 	#	DIAHORA=$(date +"%d%m%Y-%T" | sed 's/://g')
@@ -64,6 +65,11 @@ function sh_config {
 
 function log_error {
 	printf "%30s:%-06d] : %s => %s\n" "$1" "$2" "$3 $4" >>"$BOOTLOG"
+}
+
+msg() {
+   local msg="$1"
+   echo -e "==>${cyan}[INFO] ${yellow}${msg}${reset}"
 }
 
 function cmdlogger {
@@ -147,11 +153,15 @@ function sh_checkDependencies() {
 	done
 
 	if $errorFound; then
-		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE-------------${reset}"
-		echo "This script needs the commands listed above"
-		echo "Install them and/or make sure they are in your ${red}\$PATH${reset}"
-		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE-------------${reset}"
-		die "Installation aborted!"
+	   if ! sudo pacman -Sy "${PACKAGEDEP[@]}" --needed --noconfirm 1>/dev/null ; then
+         echo
+         msg "${yellow}----------------------IMPOSSÍVEL CONTINUAR--------------------${reset}"
+         msg "Este script precisa dos comandos listados acima.${reset}"
+         msg "Fiz tentativa de instalar, no entanto falhou.${reset}"
+         msg "Instale-os e/ou certifique-se de que eles estejam em seu ${red}\$PATH${reset}"
+         msg "${yellow}----------------------IMPOSSÍVEL CONTINUAR--------------------${reset}"
+         die "Instalação abortada!"
+      fi
 	fi
 }
 
@@ -201,7 +211,30 @@ function sh_main {
 	fi
 }
 
+sh_usage() {
+   cat <<-EOF
+    ${cyan}$APP - $APPDESC${reset}
+    Uso: $APP [options] <directory>
+
+    Options:
+      -q          Quiet mode (suppress progress messages)
+      -n          Disable colors in the output
+      -z          Use pigz for compression
+      -s          Use pzstd for compression (default)
+      -g          Use gzip for compression
+      -x          Use xz for compression
+      (normal)    Create tar archive without additional compression
+EOF
+   exit 1
+}
+
 sh_config
+
+# Display usage information if no arguments are passed
+if [[ $# -eq 0 || $1 = @(-h|--help) || $1 = "-h" || $1 = "--help" || $1 = "help" || $1 = "-help" ]]; then
+   sh_usage
+fi
+
 sh_checkDependencies
 
 #if [ "$(id -u)" -ne 0 ]; then
@@ -214,22 +247,6 @@ else
   if [ "$(id -u)" -ne 0 ]; then
     die "$APP: need root perms to continue, exiting."
   fi
-fi
-
-# Display usage information if no arguments are passed
-if [[ $# -eq 0 ]]; then
-  cat <<-EOF
-    Usage: $APP [options] <directory>
-    Options:
-      -q          Quiet mode (suppress progress messages)
-      -n          Disable colors in the output
-      -z          Use pigz for compression
-      -s          Use pzstd for compression ${cyan}(default)${reset}
-      -g          Use gzip for compression
-      -x          Use xz for compression
-      (normal)    Create tar archive without additional compression
-EOF
-  exit 1
 fi
 
 # Process command line options using getopts
