sex 20 dez 2024 22:52:20 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-chroot b/chili-chroot
--- a/chili-chroot
+++ b/chili-chroot
@@ -3,7 +3,7 @@
 #  chili-chroot - chroot util compatible with all likeunix
 #
 #  Created: 2019/04/05
-#  Altered: 2024/04/27
+#  Altered: 2024/12/18 - 10:37 -04
 #
 #  Copyright (c) 2019-2024, Vilmar Catafesta <vcatafesta@gmail.com>
 #  Chili GNU/Linux - https://github.com/vcatafesta
@@ -128,5 +128,14 @@ sh_init_bind() {
 	fi
 }
 
+sh_checkroot() {
+	[[ $1 = "-Qq" ]] && return
+	if [ "$(id -u)" != "0" ]; then
+		printf "${red} error: You cannot perform this operation unless you are root!\n"
+		exit 1
+	fi
+}
+
 sh_setenvironment
+sh_checkroot
 sh_init_bind "$@"
diff --git a/chili-contrib-20221209-1-any/usr/bin/chili-chroot b/chili-contrib-20221209-1-any/usr/bin/chili-chroot
--- a/chili-contrib-20221209-1-any/usr/bin/chili-chroot
+++ b/chili-contrib-20221209-1-any/usr/bin/chili-chroot
@@ -1,100 +1,141 @@
 #!/usr/bin/env bash
 
-#  chili-chroot - chroot util compatible with:
-#  Chili GNU/Linux - https://github.com/vcatafesta/ChiliOS
-#  Chili GNU/Linux - https://chililinux.com
-#  Chili GNU/Linux - https://chilios.com.br
-#  MazonOS GNU/Linux - http://mazonos.com
+#  chili-chroot - chroot util compatible with all likeunix
 #
 #  Created: 2019/04/05
-#  Altered: 2022/05/23
+#  Altered: 2024/12/18 - 10:37 -04
 #
-#  Copyright (c) 2019-2022, Vilmar Catafesta <vcatafesta@gmail.com>
+#  Copyright (c) 2019-2024, Vilmar Catafesta <vcatafesta@gmail.com>
+#  Chili GNU/Linux - https://github.com/vcatafesta
+#  					 	https://github.com/chililinux
+#							https://github.com/voidlinux-br/void-installer
+#  					 	https://chililinux.com
+#  					 	https://chilios.com.br
 #
-#  This program is free software; you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation; either version 2 of the License, or
-#  (at your option) any later version.
+#  Redistribution and use in source and binary forms, with or without
+#  modification, are permitted provided that the following conditions
+#  are met:
+#  1. Redistributions of source code must retain the above copyright
+#     notice, this list of conditions and the following disclaimer.
+#  2. Redistributions in binary form must reproduce the above copyright
+#     notice, this list of conditions and the following disclaimer in the
+#     documentation and/or other materials provided with the distribution.
 #
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
-#
-#  You should have received a copy of the GNU General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-
-#  chili-chroot uses quite a few external programs during its execution. You
-#  need to have at least the following installed for makepkg to function:
-#     awk, bsdtar (libarchive), bzip2, coreutils, fakeroot, file, find (findutils),
-#     gettext, gpg, grep, gzip, sed, tput (ncurses), xz
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
+#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
+#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
+#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
+#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
+#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
+#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #########################################################################
-LIBRARY=${LIBRARY:-'/usr/share/fetch'}
-source /usr/lib/lsb/init-functions
-source "$LIBRARY"/core.sh
+shopt -s extglob
+#findmount
 
-chilichroot2() {
-	if [ $# -gt 0 ]; then
-		CHROOTDIR="$1"
-		log_wait_msg "Criando CHROOT on $CHROOTDIR"
-		mkdir -pv $CHROOTDIR
-		for i in /dev /dev/pts /proc /sys /run; do
-			log_wait_msg "Binding $CHROOTDIR$i"
-			sudo mount -B ${i} ${CHROOTDIR}${i}
-		done
-		log_wait_msg "Iniciando CHROOT at $CHROOTDIR"
-		sudo chroot ${CHROOTDIR}
-		log_wait_msg "Unbinding $CHROOTDIR"
-		sudo umount -rl ${CHROOTDIR}/run
-		sudo umount -rl ${CHROOTDIR}/sys
-		sudo umount -rl ${CHROOTDIR}/proc
-		sudo umount -rl ${CHROOTDIR}/dev/pts
-		sudo umount -rl ${CHROOTDIR}/dev
-		#sudo grub-install /dev/sdb
-		#sudo update-grub /dev/sdb
+sh_setenvironment() {
+	declare -g ON_MOUNTS=()
+	bold=$(tput bold)
+	white="${bold}$(tput setaf 7)"
+	black="${bold}$(tput setaf 0)"
+	red=$(tput bold)$(tput setaf 196)
+	green=$(tput setaf 2)
+	yellow=$(tput bold)$(tput setaf 3)
+	blue=$(tput setaf 4)
+	pink=$(tput setaf 5)
+	cyan=$(tput setaf 6)
+	orange=$(tput setaf 3)
+	purple=$(tput setaf 125)
+	violet=$(tput setaf 61)
+	COL_NC='\e[0m' # No Color
+	COL_LIGHT_GREEN='\e[1;32m'
+	COL_LIGHT_RED='\e[1;31m'
+	TICK="${white}[${COL_LIGHT_GREEN}✓${COL_NC}${white}]"
+	CROSS="${white}[${COL_LIGHT_RED}✗${COL_NC}${white}]"
+	INFO="[i]"
+	DONE="${COL_LIGHT_GREEN} done!${COL_NC}"
+	OVER="\\r\\033[K"
+	DOTPREFIX="  ${black}::${reset} "
+}
+
+msg() {
+	local retval="${PIPESTATUS[0]}"
+
+	if [[ $retval -eq 0 ]]; then
+		printf "  %b %s\\n" "${TICK}" "${*}"
 	else
-		echo "Uso: chili-chroot /mnt/full"
+		printf "  %b %s\\n" "${CROSS}" "${*}"
 	fi
 }
 
-chrootmount() {
-	sudo mount "$@"
+sh_ignore_error() {
+	"$@" 2>/dev/null
+	return 0
 }
 
-chilichroot() {
+sh_chroot_maybe_add_mount() {
+	local cond=$1
+	shift
+	if eval "$cond"; then
+		sh_mount_bind "$@"
+	fi
+}
+
+sh_mount_bind() {
+	mount "$@" 2>&1
+	ON_MOUNTS+=("$2")
+}
+
+sh_stop_bind() {
+	if ((${#ON_MOUNTS[@]})); then
+		msg "Unbinding $CHROOTDIR"
+		umount -R "${ON_MOUNTS[@]}" >/dev/null 2>&-
+	fi
+	umount -R $CHROOTDIR/etc/resolv.conf >/dev/null 2>&-
+	unset ON_MOUNTS
+}
+
+sh_init_bind() {
 	if test $# -ge 1; then
 		CHROOTDIR="$1"
 		[[ ${CHROOTDIR} = '.' ]] && CHROOTDIR=${PWD}
-		log_wait_msg "Generate dirs in $CHROOTDIR"
-		for i in /proc /sys /dev /dev/pts /dev/shm /run /tmp /hostrun; do
-			mkdir -pv ${CHROOTDIR}${i}
+		for i in /proc /etc /sys /dev /dev/pts /dev/shm /run /tmp; do
+			if [[ ! -d "${CHROOTDIR}${i}" ]]; then
+				msg "Generate ${i} in $CHROOTDIR"
+				mkdir -p "${CHROOTDIR}${i}" >/dev/null 2>&-
+			fi
 		done
-		log_wait_msg "Mounting on $CHROOTDIR"
-		chrootmount proc "${CHROOTDIR}/proc" -t proc -o nosuid,noexec,nodev &&
-			chrootmount sys "${CHROOTDIR}/sys" -t sysfs -o nosuid,noexec,nodev,ro &&
-			chrootmount udev "${CHROOTDIR}/dev" -t devtmpfs -o mode=0755,nosuid &&
-			chrootmount devpts "${CHROOTDIR}/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
-			chrootmount shm "${CHROOTDIR}/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
-			chrootmount /run "${CHROOTDIR}/run" --bind &&
-			chrootmount /run "${CHROOTDIR}/hostrun" --bind &&
-			chrootmount tmp "${CHROOTDIR}/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
-		log_wait_msg "Iniciando CHROOT at $CHROOTDIR"
-		sudo chroot ${CHROOTDIR}
-		log_wait_msg "Unbinding $CHROOTDIR"
-		sudo umount -r "${CHROOTDIR}/proc"
-		sudo umount -r "${CHROOTDIR}/sys"
-		sudo umount -r "${CHROOTDIR}/dev/pts"
-		sudo umount -r "${CHROOTDIR}/dev/shm"
-		sudo umount -r "${CHROOTDIR}/dev"
-		sudo umount -r "${CHROOTDIR}/run"
-		sudo umount -r "${CHROOTDIR}/hostrun"
-		sudo umount -r "${CHROOTDIR}/tmp"
-		#sudo grub-install /dev/sdb
-		#sudo update-grub /dev/sdb
+
+		touch "$CHROOTDIR/etc/resolv.conf"
+		sh_mount_bind proc "${CHROOTDIR}/proc" -t proc -o nosuid,noexec,nodev &&
+			sh_mount_bind sys "${CHROOTDIR}/sys" -t sysfs -o nosuid,noexec,nodev,ro &&
+			sh_ignore_error sh_chroot_maybe_add_mount "[[ -d '$CHROOTDIR/sys/firmware/efi/efivars' ]]" \
+				efivarfs "$CHROOTDIR/sys/firmware/efi/efivars" -t efivarfs -o nosuid,noexec,nodev &&
+			sh_mount_bind udev "${CHROOTDIR}/dev" -t devtmpfs -o mode=0755,nosuid &&
+			sh_mount_bind devpts "${CHROOTDIR}/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
+			sh_mount_bind shm "${CHROOTDIR}/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
+			sh_mount_bind run "${CHROOTDIR}/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
+			sh_mount_bind tmp "${CHROOTDIR}/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid &&
+			sh_mount_bind --bind /etc/resolv.conf $CHROOTDIR/etc/resolv.conf
+
+		msg "Starting CHROOT at $CHROOTDIR"
+		chroot ${CHROOTDIR}
+		sh_stop_bind
 	else
-		printf "ERROR: No chroot directory specified\n"
+		msg "Uso: void-chroot /mnt/full"
 	fi
 }
 
-chilichroot "$@"
+sh_checkroot() {
+	[[ $1 = "-Qq" ]] && return
+	if [ "$(id -u)" != "0" ]; then
+		printf "${red} error: You cannot perform this operation unless you are root!\n"
+		exit 1
+	fi
+}
+
+sh_setenvironment
+sh_checkroot
+sh_init_bind "$@"
