sáb 15 fev 2025 03:19:19 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-setfont b/chili-setfont
--- a/chili-setfont
+++ b/chili-setfont
@@ -2,9 +2,10 @@
 #shellcheck disable=SC2145,SC2001,SC2188,SC2015,SC2155,SC2317,SC2320,SC2291,SC2034,SC2120,SC2086,SC2319
 #shellcheck disable=SC2016,SC2154,SC2207,SC2166,SC2128,SC2059,SC2140,SC2031,SC2030,SC2036,SC2119,SC2027
 
-#  chili-setfont - utilitario para exibibir e setar fontes do console
+#  chili-setfont - utilitario para exibibir e definir fonte do console
 #  Created: 2022/12/24
 #  Altered: 2024/04/12
+#  Updated: sáb 15 fev 2025 02:49:14 -04
 #
 #  Copyright (c) 2022-2024, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
@@ -40,56 +41,80 @@ export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
 shopt -s extglob
 
 #system
-readonly APP="${0##*/}"
-readonly _VERSION_='3.01.20240412'
-readonly distro=$(uname -n)
-readonly DEPENDENCIES=(dialog setfont tput)
+declare APP="${0##*/}"
+declare _VERSION_='3.02.15.20250215'
+declare APPDESC="utilitario para exibibir e definir fonte do console"
+declare ccabec="Chili Linux - $APP - v$_VERSION_ - $APPDESC"
+declare DEPENDENCIES=(dialog setfont tput)
+declare dialogRcFile="$HOME/.dialogrc"
 
-function sh_setfont() {
-	local arrdir=('/usr/share/consolefonts' '/usr/share/kbd/consolefonts')
-	local array
-	local fonts
-	local font
-	local xglob="$*"
-	local x
-	local i
+cleanup() {
+	rm -f "$dialogRcFile"
+}
+#trap cleanup EXIT
 
-	[[ $# -lt 1 ]] && xglob="*.gz"
-	for i in "${arrdir[@]}"; do
-		if test -d "$i"; then
-			pushd "$i" &>/dev/null || die "ERRO: no access $i"
-			mapfile -t fonts <<<"$(printf "%s\n" $xglob)"
-			popd &>/dev/null || return 1
-		fi
-	done
+sh_create_dialogrc() {
+	cat >"$dialogRcFile" <<EOF
+screen_color = (white,black,off)
+dialog_color = (white,black,off)
+title_color = (cyan,black,on)
+border_color = dialog_color
+shadow_color = (black,black,on)
+button_inactive_color = dialog_color
+button_key_inactive_color = dialog_color
+button_label_inactive_color = dialog_color
+button_active_color = (white,cyan,on)
+button_key_active_color = button_active_color
+button_label_active_color = (black,cyan,on)
+tag_key_selected_color = (white,cyan,on)
+item_selected_color = tag_key_selected_color
+form_text_color = (BLUE,black,ON)
+form_item_readonly_color = (green,black,on)
+itemhelp_color = (white,cyan,off)
+inputbox_color = dialog_color
+inputbox_border_color = dialog_color
+searchbox_color = dialog_color
+searchbox_title_color = title_color
+searchbox_border_color = border_color
+position_indicator_color = title_color
+menubox_color = dialog_color
+menubox_border_color = border_color
+item_color = dialog_color
+tag_color = title_color
+tag_selected_color = button_label_active_color
+tag_key_color = button_key_inactive_color
+check_color = dialog_color
+check_selected_color = button_active_color
+uarrow_color = screen_color
+darrow_color = screen_color
+form_active_text_color = button_active_color
+gauge_color = title_color
+border2_color = dialog_color
+searchbox_border2_color = dialog_color
+menubox_border2_color = dialog_color
+separate_widget = ''
+tab_len = 0
+visit_items = off
+use_shadow = off
+use_colors = on
+EOF
+	export DIALOGRC="$dialogRcFile"
+}
 
-	if [[ ${#fonts[*]} -eq 0 ]]; then
-		die "no fonts found in:" "\n${arrdir[0]}\n${arrdir[1]}"
+# Testa se o terminal suporta caracteres gráficos estendidos
+sh_ascii_lines() {
+	#Isso força o dialog a usar caracteres ASCII básicos para as bordas.
+	#if [[ "$LANG" =~ 'UTF-8' ]]; then
+	if [[ "$(printf '\u250C')" =~ "┌" ]]; then
+		export NCURSES_NO_UTF8_ACS=1 # Terminal suporta ACS
+	else
+		export NCURSES_NO_UTF8_ACS=0 # Terminal NÃO suporta ACS
 	fi
+}
 
-	for i in "${fonts[@]}"; do
-		x="$i"
-		x="${i%%.gz*}"
-		x="${x%%.psf*}"
-		x="${x%%.psfu*}"
-		array+=("$x")
-		array+=("$i")
-	done
-
-	while :; do
-		font=$(dialog \
-			--backtitle "Chili Linux setfont v$_VERSION_" \
-			--title "Chili Linux setfont v$_VERSION_" \
-			--menu "Escolha uma fonte:" \
-			0 0 14 \
-			"${array[@]}" 2>&1 >/dev/tty)
-
-		if [[ $? -eq 1 ]]; then
-			exit
-		fi
-		echo -e "Fonte escolhida: $font"
-		setfont "$font"
-	done
+sh_setEnvironment() {
+	[[ ! -e "$dialogRcFile" ]] && sh_create_dialogrc
+	sh_ascii_lines
 }
 
 function sh_setvarcolors() {
@@ -156,9 +181,55 @@ function check_deps() {
 	fi
 }
 
+function sh_setfont() {
+	local arrdir=('/usr/share/consolefonts' '/usr/share/kbd/consolefonts')
+	local array
+	local fonts
+	local font
+	local xglob="$*"
+	local x
+	local i
+
+	[[ $# -lt 1 ]] && xglob="*.gz"
+	for i in "${arrdir[@]}"; do
+		if test -d "$i"; then
+			pushd "$i" &>/dev/null || die "ERRO: no access $i"
+			mapfile -t fonts <<<"$(printf "%s\n" $xglob)"
+			popd &>/dev/null || return 1
+		fi
+	done
+
+	if [[ ${#fonts[*]} -eq 0 ]]; then
+		die "no fonts found in:" "\n${arrdir[0]}\n${arrdir[1]}"
+	fi
+
+	for i in "${fonts[@]}"; do
+		x="$i"
+		x="${i%%.gz*}"
+		x="${x%%.psf*}"
+		x="${x%%.psfu*}"
+		array+=("$x")
+		array+=("$i")
+	done
+
+	while :; do
+		font=$(dialog \
+			--default-item "$font" \
+			--backtitle "$ccabec" \
+			--title "Menu de Fontes - /usr/share/kbd/consolefonts" \
+			--menu "Escolha uma fonte:" \
+			0 0 14 \
+			"${array[@]}" 2>&1 >/dev/tty)
+
+		if [[ $? -eq 1 ]]; then
+			exit
+		fi
+		echo -e "Fonte escolhida: $font"
+		setfont "$font"
+	done
+}
+
 sh_setvarcolors
-# debug
-#export PS4=$'${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
-#set -x
+sh_setEnvironment
 check_deps
 sh_setfont "$@"
