ter 17 out 2023 02:30:24 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-runimage b/chili-runimage
--- a/chili-runimage
+++ b/chili-runimage
@@ -7,7 +7,7 @@
 #
 #  chili-runimage
 #  Created: 2023/04/25
-#  Altered: 2023/08/31
+#  Altered: 2023/10/16
 #
 #  Copyright (c) 2023-2023, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
@@ -32,6 +32,9 @@
 #  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 #  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+export TEXTDOMAINDIR=/usr/share/locale
+export TEXTDOMAIN=chili-runimage
+
 #debug
 export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
 #set -x
@@ -39,11 +42,11 @@ export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
 
 #system
 readonly APP="${0##*/}"
-readonly _VERSION_='1.1.16-20230831'
-readonly DEPENDENCIES=('tput' 'printf' 'qemu-system-x86_64')
-readonly PACKAGEDEP=([tput]='ncurses' [printf]='coreutils' [qemu-system-x86_64X]='qemu')
-readonly xmem='16G'
+readonly _VERSION_='1.2.00-20231016'
+readonly DEPENDENCIES=('tput' 'printf' 'qemu-system-x86_64' 'gettext')
+readonly PACKAGEDEP=([tput]='ncurses' [printf]='coreutils' [qemu - system - x86_64X]='qemu' [gettext]='gettext')
 readonly iface_bridge='br0'
+declare xmem='16G'
 declare -i uefi=0
 declare -i bridge=0
 declare -a qemu_options=()
@@ -55,8 +58,13 @@ function cleanup_working_dir {
 	fi
 }
 
+function DOT {
+	printf "%s" "${blue}:: ${reset}"
+}
+
 function die {
-	local msg=$1; shift
+	local msg=$1
+	shift
 	printf "  %b %s\\n" "${CROSS}" "${bold}${red}${msg}"
 	exit 1
 }
@@ -72,46 +80,20 @@ function log_msg() {
 }
 
 function sh_checkRoot {
-	local str="Root user check"
+	local str="$(gettext "Verificação de usuário root")"
 	if [[ "$(id -u)" != "0" ]]; then
-		die "${red} error: you cannot perform this operation unless you are root."
+		die "${red}$(gettext "erro: você não pode executar esta operação a menos que seja root")"
 	fi
 	printf "  %b %s\\n" "${TICK}" "${str}"
 	return 0
 }
 
-function sh_version {
-	printf "${orange}${0##*/} v${_VERSION_}${reset}\n"\
-"   ${bold}Copyright (C) 2023 vcatafesta@gmail.com\n"\
-"   GPLv3+ License: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>\n"\
-"   This is free software: you are free to change and redistribute it.\n"\
-"   THERE IS NO WARRANTY, to the fullest extent permitted by law.${reset}\n"
-	exit 0
-}
-
-function sh_usage {
-cat <<EOF
-Usage:
-	${orange}$APP ${reset} [Options]
-
-Options:
-	-h|--help              print this help
-	-u|--uefi              set boot type to 'UEFI'
-	-b|--bridge            configure net as bridge
-	-n|--nocolor           remove colors from output
-	-V|--version           print version
-
-Example:
-	Run an image/disk using UEFI:
-	$ ${orange}$APP${reset} -u file.iso
-	$ ${orange}$APP${reset} -u file.img
-	$ ${orange}$APP${reset} -u /dev/sdX
-
-	Run an image/disk using BIOS:
-	$ ${orange}$APP${reset} file.iso
-	$ ${orange}$APP${reset} file.img
-	$ ${orange}$APP${reset} /dev/sdX
-EOF
+sh_version() {
+	printf "%s\n" "${black}${0##*/} v${_VERSION_}${reset}"
+	printf "\t%s\n\t%s\n\t%s\n\t%s\n" "${bold}${black}Copyright (C) 2023 vcatafesta@gmail.com" \
+		"$(gettext "Licença GPLv3+: GNU GPL versão 3 ou posterior") <https://gnu.org/licenses/gpl.html>" \
+		"$(gettext "Este é um software livre: você é livre para alterá-lo e redistribuí-lo.")" \
+		"$(gettext "NÃO HÁ GARANTIA, em toda a extensão permitida por lei.")$reset"
 	exit 0
 }
 
@@ -129,8 +111,8 @@ function sh_setenvironment {
 	pink=$(tput setaf 5)
 	cyan=$(tput setaf 6)
 	orange=$(tput setaf 3)
-	purple=$(tput setaf 125);
-	violet=$(tput setaf 61);
+	purple=$(tput setaf 125)
+	violet=$(tput setaf 61)
 	COL_NC='\e[0m' # No Color
 	COL_LIGHT_GREEN='\e[1;32m'
 	COL_LIGHT_RED='\e[1;31m'
@@ -155,72 +137,62 @@ function sh_checkDependencies {
 	declare -a missing
 
 	for d in "${DEPENDENCIES[@]}"; do
-		[[ -n $(command -v "$d") ]] && { :; } || { \
-			printf "%s\n" "${red}ERROR${reset}: Could not find command ${cyan}'$d'${reset} -> install package '${PACKAGEDEP[$d]}'"
+		[[ -n $(command -v "$d") ]] && { :; } || {
+			printf "%s\n" "${red}ERROR${reset}: $(gettext "Não foi possível encontrar o comando") ${cyan}'$d'${reset} -> $(gettext "instalar pacote") '${PACKAGEDEP[$d]}'"
 			missing+=("$d")
 			errorFound=1
 		}
 	done
-	if (( errorFound )); then
-		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE---------------"
-		echo "${black}This script needs the commands listed above"
-		echo "Install them and/or make sure they are in your \$PATH"
-		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE---------------"
-		exit 1
+
+	if ((errorFound)); then
+		echo "===================================================="
+		echo "${yellow}             $(gettext "IMPOSSÍVEL CONTINUAR")"
+		echo "${black}$(gettext "Este script precisa dos comandos listados acima")"
+		echo "${black}$(gettext "Instale-os e/ou verifique se eles estão em seu") ${red}\$PATH${reset}"
+		echo "===================================================="
+		die $(gettext "Abortando...")
 	fi
 }
 
 function filerun_bios {
 	if test $# -ge 1; then
 		if test -r $1; then
-			qemu-system-x86_64\
-				-drive file=${1},format=raw,if=none,id=disk1\
-				-device ide-hd,drive=disk1,bootindex=1\
-		    	-device virtio-scsi-pci,id=scsi0\
-				"${qemu_options[@]}"
+			qemu-system-x86_64 -drive file=${1},format=raw,if=none,id=disk1 -device ide-hd,drive=disk1,bootindex=1 -device virtio-scsi-pci,id=scsi0 "${qemu_options[@]}"
 		else
-			log_msg "${red}ERROR: ${cyan}'$1' ${red}could not read or does not exist"
-	   fi
-   else
+			log_msg "${red}ERROR: ${cyan}'$1' ${red}$(gettext "erro de leitura ou não existe")"
+		fi
+	else
 		sh_usage
-   fi
+	fi
 }
 
 function filerun_uefi {
 	if test $# -ge 1; then
 		if test -r $1; then
-		   local ovmf_code='/usr/share/edk2-ovmf/x64/OVMF_CODE.fd'
+			local ovmf_code='/usr/share/edk2-ovmf/x64/OVMF_CODE.fd'
 			local working_dir="$(mktemp -dt chili-runimage-$USER.XXX)"
 
 			if [[ ! -f '/usr/share/edk2-ovmf/x64/OVMF_VARS.fd' ]]; then
-				printf 'ERROR: %s\n' "OVMF_VARS.fd not found. Install edk2-ovmf."
+				printf 'ERROR: %s\n' "OVMF_VARS.fd $(gettext "não encontrado. Instale o pacote") edk2-ovmf."
 				exit 1
 			fi
 			cp -av -- '/usr/share/edk2-ovmf/x64/OVMF_VARS.fd' "${working_dir}/"
 
 			if [[ ${1: -4} == ".iso" ]]; then
-			  # ISO disk
-				qemu-system-x86_64\
-				 	-cdrom $1\
-				 	-boot d\
-	 				-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=off\
-					-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd\
-					"${qemu_options[@]}"
+				# ISO disk
+				qemu-system-x86_64 -cdrom $1 \
+					-boot d -drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=off -drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd "${qemu_options[@]}"
 			else
 				# RAW disk
-				qemu-system-x86_64\
-				  	-drive file=${1},format=raw,if=virtio\
-					-drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=off\
-					-drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd\
-					"${qemu_options[@]}"
+				qemu-system-x86_64 -drive file=${1},format=raw,if=virtio -drive if=pflash,format=raw,unit=0,file=${ovmf_code},read-only=off -drive if=pflash,format=raw,unit=1,file=${working_dir}/OVMF_VARS.fd "${qemu_options[@]}"
 			fi
 		else
-			log_msg "${red}ERROR: ${cyan}'$1' ${red}could not read or does not exist"
+			log_msg "${red}ERROR: ${cyan}'$1' ${red}$(gettext "erro de leitura ou não existe")"
 			sh_usage
 		fi
 	else
 		sh_usage
-   fi
+	fi
 }
 
 function sh_set_qemu_common_options {
@@ -229,19 +201,18 @@ function sh_set_qemu_common_options {
 	qemu_options+=(-cpu host)
 	qemu_options+=(-smp "$(nproc)")
 	qemu_options+=(-name 'chili-runimage')
-	qemu_options+=(-m ${xmem})
-#	qemu_options+=(-vga std)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-#	qemu_options+=(-device VGA)
-#	qemu_options+=(-device ramfb)			# ✗ not VGA compatible ✓ vgabios support ✓ UEFI support (QemuRamfbDxe)
-#	qemu_options+=(-device cirrus-vga)		# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (cirrus.ko)
-#	qemu_options+=(-device qxl)
-#	qemu_options+=(-device qxl-vga)
-	qemu_options+=(-vga virtio)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (virtio-gpu.ko)
-#	qemu_options+=(-device bochs-display)	# ✗ not VGA compatible	✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-#	qemu_options+=(-vga std)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
-#	qemu_options+=(-device qxl-vga)
-#	qemu_options+=(-device ati-vga)
-#	qemu_options+=(-vga qxl) 				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (qxl.ko) ✓ windows driver
+	#	qemu_options+=(-vga std)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
+	#	qemu_options+=(-device VGA)
+	#	qemu_options+=(-device ramfb)			# ✗ not VGA compatible ✓ vgabios support ✓ UEFI support (QemuRamfbDxe)
+	#	qemu_options+=(-device cirrus-vga)		# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (cirrus.ko)
+	#	qemu_options+=(-device qxl)
+	#	qemu_options+=(-device qxl-vga)
+	qemu_options+=(-vga virtio) # ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (virtio-gpu.ko)
+	#	qemu_options+=(-device bochs-display)	# ✗ not VGA compatible	✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
+	#	qemu_options+=(-vga std)				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (bochs-drm.ko)
+	#	qemu_options+=(-device qxl-vga)
+	#	qemu_options+=(-device ati-vga)
+	#	qemu_options+=(-vga qxl) 				# ✓ VGA compatible ✓ vgabios support ✓ UEFI support (QemuVideoDxe) ✓ linux driver (qxl.ko) ✓ windows driver
 	qemu_options+=(-display gtk)
 	qemu_options+=(-device intel-hda)
 	qemu_options+=(-audiodev pa,id=snd0,server=localhost)
@@ -257,46 +228,102 @@ function sh_set_qemu_common_options {
 #				  	-net nic,model=virtio \
 #				  	-net user \
 
+function sh_usage {
+	cat <<EOF
+$(gettext "Uso"):
+	${orange}$APP${reset} [$(gettext "Opções") [-b] [-n] [-u]]
+
+$(gettext "Opções"):
+	-h|--help              $(gettext "imprima esta ajuda")
+	-u|--uefi              $(gettext "defina o tipo de inicialização para") 'UEFI'
+	-b|--bridge            $(gettext "configurar net como ponte")
+	-n|--nocolor           $(gettext "remover cores da saída")
+	-V|--version           $(gettext "imprimir versão do aplicativo")
+	-m|--memory            $(gettext "quantidade inicial de memória de convidado")
+
+$(gettext "Exemplo"):
+	# ${orange}$APP${reset} -b -u file.iso         #$(gettext "Execute uma imagem, em ponte, usando") UEFI
+	# ${orange}$APP${reset} -u file.img            #$(gettext "Execute uma imagem, em NAT, usando") UEFI
+	# ${orange}$APP${reset} -b -u /dev/sdX         #$(gettext "Execute uma device, em ponte, usando") UEFI
+	# ${orange}$APP${reset} -m 16G -b -u /dev/sdX  #$(gettext "Execute uma device, em ponte, 16Gb memória, usando") UEFI
+
+	# ${orange}$APP${reset} file.iso               #$(gettext "Execute uma imagem usando") BIOS
+	# ${orange}$APP${reset} -b file.img            #$(gettext "Execute uma imagem, em ponte, usando") BIOS
+	# ${orange}$APP${reset} -m 16G /dev/sdX        #$(gettext "Execute uma device, 16GB memória, usando") BIOS
+EOF
+	exit 0
+}
+
 sh_setenvironment
 sh_checkDependencies
 
-OPTIONS=ubVnh
-LONGOPTIONS=uefi,bridge,version,nocolor,help
-opts=$(getopt --options=$OPTIONS --longoptions=$LONGOPTIONS --name "$0" -- "$@")
-if [ $? -ne 0 ]; then
-	sh_usage
-fi
-eval set -- "$opts"
+OPTIONS=m:ubVnh
+LONGOPTIONS=memory:,uefi,bridge,version,nocolor,help
+#if ! opts=($(getopt --options="$OPTIONS" --longoptions="$LONGOPTIONS" --name "$0" -- "$@")); then
+#	sh_usage
+#fi
+#eval set -- "${opts[*]}"
 
-while true; do
-	case "$1" in
-		-u|--uefi)  	uefi=1;shift;;
-		-b|--bridge)  	bridge=1;shift;;
-		-n|--nocolor)  sh_unsetvarcolors;shift;;
-		-V|--version)  sh_version;;
-		-h|--help)     sh_usage;;
-		--)            shift;break;;
-		*)             sh_usage;;
+opts=($(getopt --options="$OPTIONS" --longoptions="$LONGOPTIONS" --name "$0" -- "$@"))
+eval set -- "${opts[*]}"
+
+while test ${#opts[*]} -gt 0; do
+	case $1 in
+	-u | --uefi)
+		uefi=1
+		;;
+	-b | --bridge)
+		bridge=1
+		;;
+	-n | --nocolor)
+		sh_unsetvarcolors
+		;;
+	-m | --memory)
+		if [[ $2 =~ ^[0-9]+[MG]?$ ]]; then
+			xmem=$2
+			shift
+		else
+			die "$(gettext "Argumento inválido para -m. Use um formato como 16GB (por exemplo).")" >&2
+		fi
+		;;
+	-V | --version) sh_version ;;
+	-h | --help) sh_usage ;;
+	--)
+		shift
+		break
+		;;
+	:)
+		die "-$OPTARG $(gettext "requer um argumento")" >&2
+		;;
+	*)
+		die "$(gettext "operação não suportada"): $1 ($(gettext "usar -h para ajuda"))"
+		;;
 	esac
+	shift
 done
 
-sh_checkRoot
-if ((bridge)); then
-	random_mac_net0=$(python3 -c "import random; print(':'.join(['{:02x}'.format(random.randint(0, 255)) for _ in range(6)]))")
-	random_mac_net1=$(python3 -c "import random; print(':'.join(['{:02x}'.format(random.randint(0, 255)) for _ in range(6)]))")
-	echo $random_mac_net0
-	echo $random_mac_net1
-#	qemu_options+=(-netdev bridge,id=net0)
-	qemu_options+=(-netdev bridge,id=net0,br=$iface_bridge)
-	qemu_options+=(-device e1000,netdev=net0,mac=$random_mac_net0)
-	qemu_options+=(-netdev bridge,id=net1,br=$iface_bridge)
-	qemu_options+=(-device e1000,netdev=net1,mac=$random_mac_net1)
+if [[ $# > 0 ]] ; then
+	sh_checkRoot
+	qemu_options+=(-m ${xmem})
+	if ((bridge)); then
+		random_mac_net0=$(python3 -c "import random; print(':'.join(['{:02x}'.format(random.randint(0, 255)) for _ in range(6)]))")
+		random_mac_net1=$(python3 -c "import random; print(':'.join(['{:02x}'.format(random.randint(0, 255)) for _ in range(6)]))")
+		#	echo $random_mac_net0
+		#	echo $random_mac_net1
+		#	qemu_options+=(-netdev bridge,id=net0)
+		qemu_options+=(-netdev bridge,id=net0,br=$iface_bridge)
+		qemu_options+=(-device e1000,netdev=net0,mac=$random_mac_net0)
+		qemu_options+=(-netdev bridge,id=net1,br=$iface_bridge)
+		qemu_options+=(-device e1000,netdev=net1,mac=$random_mac_net1)
+	else
+		qemu_options+=(-netdev user,id=net0)
+		qemu_options+=(-device e1000,netdev=net0)
+	fi
+	if ((uefi)); then
+		filerun_uefi "$@"
+	else
+		filerun_bios "$@"
+	fi
 else
-	qemu_options+=(-netdev user,id=net0)
-	qemu_options+=(-device e1000,netdev=net0)
-fi
-if ((uefi)); then
-	filerun_uefi "$@"
-else
-	filerun_bios "$@"
+	die "${opts[*]} $(gettext "falta parâmetro de imagem/disco/device"): ($(gettext "usar -h para ajuda"))"
 fi
