upgrade

diff --git a/fetchpack b/fetchpack
--- a/fetchpack
+++ b/fetchpack
@@ -74,6 +74,8 @@ CURS_ZERO="\\033[0G"
 : ${PKG_VERSION=5}
 : ${PKG_BUILD=6}
 
+
+# core functions
 function setvarcolors(){
 	if tput setaf 1 &> /dev/null; then
 		tput sgr0; # reset colors
@@ -124,8 +126,8 @@ function unsetvarcolors(){
 	unset pink
 }
 
-function info()
-{
+
+function info(){
 #	dialog							\
 	whiptail							\
 		--title     "[debug]$0"	\
@@ -139,18 +141,18 @@ function info()
 		return $result
 }
 
-function debug()
-{
+
+function debug(){
 	info "$*"
 	return $?
 }
 
 
-function timespec()
-{
+function timespec(){
 	STAMP="$(echo `date +"%b %d %T %:z"` `hostname`) "
 	return 0
 }
+
 
 function log_info_msg(){
 	echo -n -e "${BMPREFIX}${@}"
@@ -160,8 +162,8 @@ function log_info_msg(){
 	return 0
 }
 
-function evaluate_retval()
-{
+
+function evaluate_retval(){
 	local error_value="${?}"
 
 	if [ ${error_value} = 0 ]; then
@@ -172,39 +174,39 @@ function evaluate_retval()
 	return ${error_value}
 }
 
-function log_failure_msg2()
-{
+
+function log_failure_msg2(){
 	echo -n -e "${BMPREFIX}${@}"
 	echo -e "${CURS_ZERO}${FAILURE_PREFIX}${SET_COL}${FAILURE_SUFFIX}"
 	echo "FAIL" >> ${BOOTLOG}
 	return 0
 }
 
-function log_wait_msg()
-{
+
+function log_wait_msg(){
 	echo -n -e "${BMPREFIX}${@}"
 	echo -e "${CURS_ZERO}${WAIT_PREFIX}${SET_COL}${WAIT_SUFFIX}"
 	echo " OK" >> ${BOOTLOG}
 	return 0
 }
 
-function log_success_msg2()
-{
+
+function log_success_msg2(){
 	echo -n -e "${BMPREFIX}${@}"
 	echo -e "${CURS_ZERO}${SUCCESS_PREFIX}${SET_COL}${SUCCESS_SUFFIX}"
 	echo " OK" >> ${BOOTLOG}
 	return 0
 }
 
-function die()
-{
+
+function die(){
 	local mesg=$1; shift
    log_failure_msg2 "${red}$mesg" "$@" >&2
 	exit 1
 }
 
-function runcmd()
-{
+
+function runcmd(){
 	if (( EUID != 0 )); then
 		msg "Privilege escalation required"
 		if sudo -v &>/dev/null && sudo -l &>/dev/null; then
@@ -217,8 +219,8 @@ function runcmd()
 	fi
 }
 
-function sh_splitpkg()
-{
+
+function sh_splitpkg(){
 	file=${1}
 	#pkg_re='^([a-z-]+)(-)([0-9\\.]+)(-)([0-9])(-)(.*)(.chi.zst)$'
 	#pkg_re='([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)-(([0-9]+(\.[0-9]+)*)(-([0-9]+))?)-([^.]+).*'
@@ -228,7 +230,28 @@ function sh_splitpkg()
 	pkg_folder_dir=$(echo ${file%/*})							#remove arquivo deixando somente o diretorio/repo
 	pkg_fullname=$(echo ${file##*/})    						#remove diretorio deixando somente nome do pacote
 
-	[[ $pkg_fullname =~ $pkg_re ]] &&
+	arr=($(echo $pkg_fullname | awk 'match($0, /(.+)-(([^-]+)-([0-9]+))-([^.]+)\.chi\.zst/, array) {
+			print array[0]
+			print array[1]
+			print array[2]
+		   print array[3]
+		   print array[4]
+    		print array[5]
+    		print array[6]
+			}'))
+	pkg_fullname="${arr[0]}"
+	pkg_base="${arr[1]}"
+	pkg_version_build="${arr[2]}"
+	pkg_version="${arr[3]}"
+	pkg_build="${arr[4]}"
+	pkg_arch="${arr[5]}"
+	pkg_base_version="${arr[0]}-${arr[4]}"
+	aPKGSPLIT=($pkg_folder_dir $pkg_fullname $pkg_arch $pkg_base $pkg_base_version $pkg_version $pkg_build)
+	return $?
+}
+
+
+function sh_splitpkgNEW(){
 		pkg_fullname=${BASH_REMATCH[0]}
 		pkg_base=${BASH_REMATCH[1]}
 		pkg_version_build=${BASH_REMATCH[2]}
@@ -249,8 +272,8 @@ function sh_splitpkg()
 	return $?
 }
 
-function sh_splitpkgOLD()
-{
+
+function sh_splitpkgOLD(){
 	local PRG='chi.zst'
 	local file=${1}
 	local pkg_folder_dir
@@ -321,31 +344,7 @@ function sh_splitpkgOLD()
 	return $?
 }
 
-function summary()
-{
-	local -i filecount=$1; shift
-	local seenarch= seen= arch= name=
-	local -r pkg_re='(.+)-[^-]+-[0-9]+-([^.]+)\.pkg.*'
-
-	msg "Candidate packages:"
-	while read -r pkg; do
-		if (( verbose >= 3 )); then
-			pkg =~ $pkg_re ]] && name=${BASH_REMATCH[1]} arch=${BASH_REMATCH[2]}
-			if [[ -z $seen || $seenarch != "$arch" || $seen != "$name" ]]; then
-				seen=$name seenarch=$arch
-				printf '%s (%s):\n' "${name##*/}" "$arch"
-			fi
-			printf '  %s\n' "${pkg##*/}"
-		elif (( verbose >= 2 )); then
-			printf "%s$delim" "$pkg"
-		else
-			printf "%s$delim" "${pkg##*/}"
-		fi
-	done < <(printf '%s\n' "$@" | pacsort --files)
-}
-
-function size_to_human()
-{
+function size_to_human(){
 	awk -v size="$1" '
 	BEGIN {
 		suffix[1] = "B"
@@ -517,7 +516,6 @@ function init()
 	elif (( move )); then
 		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
 	fi
-	#summary "$pkgcount" "${candidates[@]}"
 	echo
 	msg "$output (disk space saved: %s)" "$(size_to_human "$totalsaved")"
 }
@@ -756,7 +754,7 @@ mainold1(){
 	fi
 }
 
-function main()
+function mainOLD()
 {
 	local nfiles=0
 	local pkg=
@@ -784,6 +782,8 @@ function main()
 				AllFilesPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort)
 			fi
 		fi
+
+		# find "$PWD" -iname "zip*.chi.zst" | sort -Vr | sed -r 's/([^0-9])-([^0-9])/\1§\2/g' | sort -t- -k1,1 -u | sed 's/§/-/g'
 
 		arrayfull=("${AllFilesPackages[@]}")
 
@@ -890,7 +890,6 @@ function main()
 		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
 		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
 	fi
-	#summary "$pkgcount" "${candidates[@]}"
 	echo
 	if (( dryrun )); then
 		msg "${yellow}$output finish dry-run (files found: $pkgcount) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
@@ -899,8 +898,126 @@ function main()
 	fi
 }
 
-function usage()
+function main()
 {
+	local nfiles=0
+	local pkg=
+	local pkgInAll=
+	local pkg_base=
+	local pkg_search=
+	local candidates=()
+	local cachedir
+
+	for cachedir in "${cachedirs[@]}"
+	do
+		[[ -d $cachedir ]]            || die "Error: cachedir '$cachedir' does not exist or is not a directory"
+		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
+
+		#E eventualmente pode trocar a regex por umas dessas versões, se ainda quiser seguir com awk
+		#'[0-9]+([.][0-9]+)+'
+		#'-[0-9]+(.[0-9]+)+'
+		#'-[0-9]+([.][0-9]+)+'
+
+		if [ $# -lt 1 ]; then
+			#AllFilesPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort )
+			#AllNewPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort -Vr | sed -r 's/([^0-9])-([^0-9])/\1§\2/g' | sort -t- -k1,1 -u | sed 's/§/-/g')
+  			#AllOldPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort -Vr | awk -F '[0-9]+(.[0-9]+)+' 'lista[$1]++')
+			#using awk
+  			AllOldPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort -Vr | awk -F '[0-9]+([.][0-9]+)+' 'lista[$1]++') 		#OK
+  			#AllNewPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort -V | awk -F '[0-9]+(.[0-9]+)+' '!lista[$1]++')
+			#using sort
+			#AllOldPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort -V | rev | tr - '\t' | uniq -f3 | tr '\t' - | rev)
+			#AllNewPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort -Vr | rev | tr - '\t' | uniq -f3 | tr '\t' - | rev | tac)
+		else
+			#AllFilesPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort)
+		   #AllNewPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort -Vr | sed -r 's/([^0-9])-([^0-9])/\1§\2/g' | sort -t- -k1,1 -u | sed 's/§/-/g')
+			#AllOldPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort -Vr | awk -F '[0-9]+(.[0-9]+)+' 'lista[$1]++')
+			#using awk
+			AllOldPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort -Vr | awk -F '[0-9]+([.][0-9]+)+' 'lista[$1]++')   #OK
+			#AllNewPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort -V | awk -F '[0-9]+(.[0-9]+)+' '!lista[$1]++')
+			#using sort
+			#AllOldPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort -V | rev | tr - '\t' | uniq -f3 | tr '\t' - | rev)
+			#AllNewPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort -Vr | rev | tr - '\t' | uniq -f3 | tr '\t' - | rev | tac)
+		fi
+		#arrayfull=("${AllFilesPackages[@]}")
+		arrayfull=("${AllOldPackages[@]}")
+		#arr=(${AllOldPackages[*]})
+		#nfiles=${#arr[*]}
+
+		if (( dryrun )); then
+	   	echo "${white}running mode => ${red}DRY-RUN"
+		elif (( delete )); then
+	   	echo "${white}running mode => ${red}DELETE"
+		elif (( move )); then
+	   	echo "${white}running mode => ${red}MOVE"
+		fi
+
+		while read -r pkgInAll;do
+			sh_splitpkg ${pkgInAll}
+			pkg_base=${aPKGSPLIT[$PKG_BASE]}
+			[[ -z "$pkg_base" ]] &&	continue
+			(( pkgNumber++ ))
+
+			if (( verbose >= 3 )); then
+				printf "     ${white}candidate package ${purple}(%04d) ${green}[%42s]${purple}(%04d)${blue} => %s\n" "$pkgNumber" "$pkg_base" "$pkgNumber" "${pkgInAll}"
+			fi
+
+			candidates+=("${pkgInAll}")
+			[[ -e "${pkgInAll}.desc" ]] && candesc+=("${pkgInAll}.desc")
+		done < <(printf '%s\n' "$arrayfull")
+		popd >/dev/null 2>&1
+	done
+
+	if (( ! ${#candidates[*]} )); then
+		echo
+		printf "${red}  E  NO packages found for pruning\n"
+		exit 0
+	fi
+
+	if (( verbose )); then
+		nfiles=0
+		while read -r pkg
+		do
+			sh_splitpkg ${pkg}
+			pkg_base=${aPKGSPLIT[$PKG_BASE]}
+			if (( verbose >= 2 )); then
+				(( nfiles++ ))
+				printf "     ${white}    found package ${purple}(%04d) ${green}[%42s]${purple}(%04d)${red} => %s\n" "$nfiles" "$pkg_base" "$nfiles" "${pkg}"
+			fi
+		done < <(printf '%s\n' "${candidates[@]}")
+	fi
+
+	if (( verbose )); then
+		nfiles=0
+		while read -r pkg
+		do
+			printf "${red}%-79s\t${green} => %s\n" "${pkg}" "${candesc[nfiles]}"
+			(( nfiles++ ))
+		done < <(printf '%s\n' "${candidates[@]}")
+	fi
+
+	pkgcount=${#candidates[*]}
+	totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	totalsaved+=$(printf '%s\0' "${candesc[@]}"   | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	set -o errexit # Exit immediately if a pipeline returns non-zero.
+
+	(( verbose )) && cmdopts+=(-v)
+	if (( delete )); then
+		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 rm "${cmdopts[@]}"
+	elif (( move )); then
+		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+	fi
+	printf "\n"
+	if (( dryrun )); then
+		msg "${yellow}$output finish dry-run (files found: $pkgcount) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
+	else
+		msg "$output (files found: $pkgcount) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
+	fi
+}
+
+function usage(){
 	cat <<EOF
 A flexible cache cleaning utility.
 Usage: ${myname} <operation> [options] [targets...]
@@ -982,6 +1099,7 @@ fi
 if [[ -z $cachedirs ]]; then
 	cachedirs=("/var/cache/fetch/archives")
 #	cachedirs+=("${PKGDIR:=/var/cache/fetch/archives}")
+#	cachedirs=("${GITDIR:=/var/cache/fetch/archives}")
 fi
 
 # sanity checks
