upgrade

diff --git a/fetchpack b/fetchpack
--- a/fetchpack
+++ b/fetchpack
@@ -6,7 +6,6 @@ declare    delim=$'\n' keep=3 movedir= scanarch=
 declare -a cachedirs=() candidates=() cmdopts=() whitelist=() blacklist=()
 declare -i delete=0 dryrun=0 filecount=0 move=0 needsroot=0 totalsaved=0 verbose=0
 
-
 QUIET=0
 USE_COLOR='y'
 IFS=$' \t\n'
@@ -107,11 +106,16 @@ function setvarcolors()
 
 function info()
 {
-	whiptail							\
+	dialog							\
 		--title     "[debug]$0"	\
 		--backtitle "$0"			\
-		--msgbox    "$*"			\
+		--yesno     "$1"			\
 		15 100
+		result=$?
+		if (( $result )); then
+			exit
+		fi
+		return $result
 }
 
 function debug()
@@ -297,8 +301,6 @@ function sh_splitpkgOLD()
 	return $?
 }
 
-
-
 function summary()
 {
 	local -i filecount=$1; shift
@@ -367,26 +369,13 @@ Usage: ${myname} <operation> [options] [targets...]
     -r, --remove          remove candidate packages.
 
   Options:
-    --min-atime <time>
-    --min-mtime <time>    keep packages with an atime/mtime that is not older
-                          than the time given, even if this means keeping more
-                          than specified through the '--keep' option. Accepts
-                          arguments according to 'info "Date input formats"',
-                          e.g. '30 days ago'.
-    -a, --arch <arch>     scan for "arch" (default: all architectures).
     -c, --cachedir <dir>  scan "dir" for packages. can be used more than once.
                           (default: read from /etc/fetch/fetch.conf).
     -f, --force           apply force to mv(1) and rm(1) operations.
     -h, --help            display this help message and exit.
-    -i, --ignore <pkgs>   ignore "pkgs", comma-separated. Alternatively, specify
-                          "-" to read package names from stdin, newline-
-                          delimited.
-    -k, --keep <num>      keep "num" of each package in the cache (default: 3).
         --nocolor         remove color from output.
     -q, --quiet           minimize output
-    -u, --uninstalled     target uninstalled packages.
     -v, --verbose         increase verbosity. specify up to 3 times.
-    -z, --null            use null delimiters for candidate names (only with -v
                           and -vv).
 
 EOF
@@ -530,8 +519,330 @@ function cleanup()
 	msg "Exiting.."
 	exit
 }
-
 trap cleanup SIGINT SIGTERM
+
+join(){
+	{
+		local indelimiter="${1- }"
+		local outdelimiter="${2-.}"
+	}
+
+	local car
+	local cdr
+	local IFS
+
+	IFS="${indelimiter}"
+	read -t 1 car cdr || return
+	test "${cdr}" || { echo "${car}" ; return ; }
+	echo "${car}${outdelimiter}${cdr}" | ${FUNCNAME} "${indelimiter}" "${outdelimiter}"
+}
+
+filter()
+{
+	local pkg_base=$1
+	local file_search=$2
+	local pkg_search=
+	local pkgInAll=$3
+
+	sh_splitpkg ${file_search}
+	pkg_search=${aPKGSPLIT[$PKG_BASE]}
+
+	if [[ "${pkg_base}" =~ "${pkg_search}" ]] && [[ "$(vercmp $pkgInAll $file_search)" -lt 0 ]]; then
+		printf "%s" "${pkgInAll}"
+	fi
+}
+
+pkgfilter()
+{
+	sh_splitpkg ${1}
+	pkg_base=${aPKGSPLIT[$PKG_BASE]}
+
+	array=$@
+	info "${array[1]})"
+
+	IFS=$'\n' read -r -d '' -a pkg < \
+		<(	if (( min_atime || min_mtime )); then
+			find "$PWD" -name '*.chi' -prune -o \( -name '*.chi.zst' -printf '%A@ %T@ %p\n' \)
+			pacsort --files --key 3 --separator ' '
+		else
+			find "$PWD" -type f -name "$pkg_base*.zst" | grep -E "*$pkg_base-([0-9])" | sort
+		fi |
+		filter "$pkg_base" "$pkg" "$1")
+#	awk '{ print $1 }'
+}
+
+mainOLD(){
+	local pkg=
+	local pkgInAll=
+	local pkg_base=
+	local pkg_search=
+	local candidates=()
+	local cachedir
+
+	for cachedir in "${cachedirs[@]}"
+	do
+		[[ -d $cachedir ]]            || die "Error: cachedir '$cachedir' does not exist or is not a directory"
+		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
+
+#		while IFS=$'\n' read -r -d '' -a cand; do
+		while IFS=$'\n' read -r -a cand; do
+			info $cand
+		done < \
+			<(	if (( min_atime || min_mtime )); then
+				find "$PWD" -name '*.chi' -prune -o \( -name '*.chi.zst' -printf '%A@ %T@ %p\n' \)
+				pacsort --files --key 3 --separator ' '
+			else
+				printf '%s\n' "$PWD"/*.chi.zst |	pacsort --files
+			fi | awk '{ print $1 }' )
+		candidates+=("${cand[@]}")
+		unset cand
+		popd >/dev/null 2>&1
+	done
+
+	files=${#candidates[*]}
+	if (( ! $files )); then
+		die "NO packages found for pruning"
+	else
+		die "${files} for pruning"
+	fi
+}
+
+function len()
+{
+	return $#
+}
+
+function seeek()
+{
+	count=0
+	while [ "x${wholist[count]}" != "x" ]
+	do
+		count=$(( $count + 1 ))
+	done
+}
+
+function ascan4()
+{
+	true=0
+	false=1
+	array=($(ls -1 /etc/ | sort ))
+	search='passwd'
+
+	if [[ "${array[@]}" =~ "${search}" ]]; then
+	    echo "${!array[*]}"
+	    echo "${BASH_REMATCH[0]}"
+	fi
+
+}
+
+function ascan3()
+{
+	local myarray="$1"
+	local match="$2"
+	printf '%s\n' "${myarray[@]}" | grep -P '^math$'
+}
+
+function ascan2()
+{
+	local myarray="$1"
+	local match="$2"
+	case "${myarray[@]}" in
+		*"$match"*)
+			return $true
+			;;
+	esac
+	return $false
+}
+
+function ascan()
+{
+  local e match="$1"
+  shift
+  for e; do [[ "$e" == "$match" ]] && return $true; done
+  return $false
+}
+
+function contains()
+{
+	local n=$#
+	local value=${!n}
+
+	for ((i=1;i < $#;i++)) {
+		if [ "${!i}" == "${value}" ]; then
+			return $i
+		fi
+	}
+	return $n
+}
+
+function teste()
+{
+	echo "+++++++++++++++++++++++++++++++"
+	array=("one" "two" "three" "four" "five six")
+	search='two'
+	contains "${array[@]}" "$search"
+	result=$?
+	len "${array[@]}"
+	nlen=$?
+
+	if (( $result > $nlen )); then
+		echo "$search not found"
+		exit
+	fi
+	echo "$search found"
+
+}
+
+mainold1(){
+	local pkg=
+	local pkgInAll=
+	local pkg_base=
+	local pkg_search=
+	local candidates=()
+	local cachedir
+
+	for cachedir in "${cachedirs[@]}"
+	do
+		[[ -d $cachedir ]]            || die "Error: cachedir '$cachedir' does not exist or is not a directory"
+		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
+
+		arrayall=($(find "$PWD" -type f -name "*.chi.zst" | sort | uniq ))
+		arraytwo=($(find "$PWD" -type f -name "*.chi.zst" | sort ))
+
+		nx=${#arraytwo[*]}
+
+#info $nx
+
+		for pkgInAll in "${arrayall[@]}"
+		do
+			sh_splitpkg ${pkgInAll}
+			pkg_base=${aPKGSPLIT[$PKG_BASE]}
+			(( npkgbase++ ))
+			[[ -z "$pkg_base" ]] && continue
+
+			for i in $(seq 0 $nx)
+			do
+				nlen=${#pkg_base}
+				pkg="${arraytwo[$i]}"
+				sh_splitpkg ${pkg}
+				pkg_search=${aPKGSPLIT[$PKG_BASE]}
+				[[ -z "$pkg_search" ]] && continue
+
+				(( npkgsearch++ ))
+#				info "${pkg_base::$nlen}"
+				[[ "${pkg_search::$nlen}" > "${pkg_search::$nlen}" ]] && break
+# info "$pkgInAll\n$pkg"
+# echo "$pkgInAll $pkg"
+				if [[ "${pkg_base}" =~ "${pkg_search}" ]] && [[ "$(vercmp $pkgInAll $pkg)" -lt 0 ]]; then
+					printf "%s\n" "${pkgInAll}"
+					candidates+=("${pkgInAll}")
+					unset arraytwo[$npkgsearch]
+				fi
+			done
+		done
+		popd >/dev/null 2>&1
+	done
+
+	if (( ! ${#candidates[*]} )); then
+		die "NO packages found for pruning"
+	fi
+}
+
+function main()
+{
+	local pkg=
+	local pkgInAll=
+	local pkg_base=
+	local pkg_search=
+	local candidates=()
+	local cachedir
+
+	for cachedir in "${cachedirs[@]}"
+	do
+		[[ -d $cachedir ]]            || die "Error: cachedir '$cachedir' does not exist or is not a directory"
+		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
+
+		if [ $# -lt 1 ]; then
+			AllFilesPackages=$(find "$PWD" -type f -iname "*.chi.zst" | sort )
+		else
+			AllFilesPackages=$(find "$PWD" -type f -iname "*.chi.zst" | grep $1 | sort)
+		fi
+
+		arrayfull=("${AllFilesPackages[@]}")
+
+		while read -r pkgInAll;do
+			sh_splitpkg ${pkgInAll}
+			pkg_base=${aPKGSPLIT[$PKG_BASE]}
+			[[ -z "$pkg_base" ]] &&	continue
+
+			(( pkgNumber++ ))
+
+			if (( verbose >= 3 )); then
+				printf "     ${white}verifying package ${purple}(%04d) ${green}[%40s]${purple}(%04d)${green} => %s\n" "$pkgNumber" "$pkg_base" "$nfiles" "${pkgInAll}"
+			fi
+
+			arr=$(find "$PWD" -type f -name "$pkg_base*.zst" | grep -E "*$pkg_base-([0-9])" | sort )
+			array=("${arr[@]}")
+			ntam=${#arr[*]}
+
+			if [[ $ntam -gt 1 ]]; then
+				continue
+			fi
+
+			while read -r pkg;do
+				sh_splitpkg ${pkg}
+				pkg_search=${aPKGSPLIT[$PKG_BASE]}
+				[[ -z "$pkg_search" ]] &&	continue
+				nlen=${#pkg_base}
+				[[ "${pkg_search::$nlen}" > "${pkg_base::$nlen}" ]] && break
+
+				if [[ "${pkg_base}" =~ "${pkg_search}" ]] && [[ "$(vercmp $pkgInAll $pkg)" -lt 0 ]]; then
+					if (( verbose == 2 )); then
+						printf "     ${white}verifying package ${purple}(%04d) ${green}[%40s]${purple}(%04d)${green} => %s\n" "$pkgNumber" "$pkg_base" "$nfiles" "${pkgInAll}"
+					fi
+					candidates+=("${pkgInAll}")
+				fi
+#			done < <(printf '%s\n' "$(find "$PWD" -type f -name "$pkg_base*.zst" | grep -E "*$pkg_base-([0-9])" | sort )")
+			done < <(printf '%s\n' "$array")
+#		done < <(printf '%s\n' "$(find "$PWD" -type f -name "*.chi.zst" | sort )")
+		done < <(printf '%s\n' "$arrayfull")
+		popd >/dev/null 2>&1
+	done
+
+	if (( ! ${#candidates[*]} )); then
+		printf "${red}  E  NO packages found for pruning\n"
+		exit 0
+	fi
+
+	echo
+	Number=0
+	while read -r pkg
+	do
+		(( Number++ ))
+		sh_splitpkg ${pkg}
+		pkg_base=${aPKGSPLIT[$PKG_BASE]}
+		printf "     ${white}found package ${purple}(%04d) ${green}[%40s]${purple}(%04d)${green} => %s\n" "$Number" "$pkg_base" "$nfiles" "${pkg}"
+	done < <(printf '%s\n' "${candidates[@]}")
+
+	pkgcount=${#candidates[*]}
+	totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	set -o errexit # Exit immediately if a pipeline returns non-zero.
+
+	(( verbose )) && cmdopts+=(-v)
+	if (( delete )); then
+		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+		printf '%s\0' "${canddesc[@]}"   | runcmd xargs -0 rm "${cmdopts[@]}"
+	elif (( move )); then
+		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+	fi
+	#summary "$pkgcount" "${candidates[@]}"
+	echo
+	if (( dryrun )); then
+		msg "$output finish dry-run (files found: $pkgcount) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
+	else
+		msg "$output (files found: $pkgcount) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
+	fi
+}
 
 OPT_SHORT=':a:c:dfhi:k:m:qrsuVvz'
 OPT_LONG=('arch:' 'cachedir:' 'dryrun' 'force' 'help' 'ignore:' 'keep:' 'move:'
@@ -586,9 +897,8 @@ fi
 
 # setting default cachedirs
 if [[ -z $cachedirs ]]; then
-	cachedirs=("${PKGDIR:=/var/cache/fetch/archives}")
-	cachedirs+=("/github/ChiliOS/packages")
-	cachedirs+=("/var/cache/fetch/archives")
+	cachedirs=("/var/cache/fetch/archives")
+#	cachedirs+=("${PKGDIR:=/var/cache/fetch/archives}")
 fi
 
 # sanity checks
@@ -606,4 +916,4 @@ if (( move || delete )); then
 	[[ $movedir && ! -w $movedir ]] && needsroot=1
 fi
 
-init $*
+main $*
